import { describe, expect, it } from "vitest";

import { configuredOperatorEmails, isConfiguredOperator, normalizeOperatorEmail } from "./operator-authorization-core";
import { generateInvitationToken, invitationExpiresAt, invitationTokenHash, invitationUsable, parseOperatorInvitationInput } from "./operator-invitations-core";

describe("operator invitation security primitives", () => {
  it("requires a private normalized allowlist rather than business ownership", () => { const env = { CAPTURE_TRACKER_OPERATOR_EMAILS: " Operator@example.test, second@example.test " }; expect(normalizeOperatorEmail(" OPERATOR@example.test ")).toBe("operator@example.test"); expect(isConfiguredOperator("operator@example.test", env)).toBe(true); expect(isConfiguredOperator("owner@example.test", env)).toBe(false); expect(configuredOperatorEmails({}).size).toBe(0); });
  it("uses 256-bit random token material and persists only a deterministic hash", async () => { const token = generateInvitationToken(new Uint8Array(32).fill(15)); expect(token).toHaveLength(64); expect(await invitationTokenHash(token)).toMatch(/^[a-f0-9]{64}$/); expect(await invitationTokenHash(token)).not.toBe(token); });
  it("requires bounded, email-safe invitation input and rejects expired/revoked/reused records", () => { expect(parseOperatorInvitationInput({ invitedEmail: "CLIENT@example.test", ownerDisplayName: "Client", businessLegalName: "Client Inc", businessDisplayName: "Client" })).toMatchObject({ invitedEmail: "client@example.test" }); expect(parseOperatorInvitationInput({ invitedEmail: "not-email", ownerDisplayName: "Client", businessLegalName: "Client Inc", businessDisplayName: "Client" })).toBeNull(); const now = new Date("2026-08-08T12:00:00.000Z"); expect(invitationExpiresAt(now).toISOString()).toBe("2026-08-11T12:00:00.000Z"); expect(invitationUsable({ status: "PENDING", expiresAt: new Date("2026-08-09T00:00:00.000Z"), revokedAt: null, acceptedAt: null }, now)).toBe(true); expect(invitationUsable({ status: "PENDING", expiresAt: new Date("2026-08-07T00:00:00.000Z"), revokedAt: null, acceptedAt: null }, now)).toBe(false); expect(invitationUsable({ status: "REVOKED", expiresAt: new Date("2026-08-09T00:00:00.000Z"), revokedAt: now, acceptedAt: null }, now)).toBe(false); expect(invitationUsable({ status: "ACCEPTED", expiresAt: new Date("2026-08-09T00:00:00.000Z"), revokedAt: null, acceptedAt: now }, now)).toBe(false); });
});
