"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireBusinessMutationContext as requireBusinessContext } from "@/lib/security/business-context";
export type CompensationActionState = { status: "idle" | "success" | "error"; message: string | null };
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/); const money = z.string().regex(/^\d{1,12}(?:\.\d{1,2})?$/);
const schema = z.object({ effectiveStart: date, effectiveEnd: date.optional().or(z.literal("")), targetLow: money.optional().or(z.literal("")), targetHigh: money.optional().or(z.literal("")), supportingNotes: z.string().trim().min(8).max(2000), reviewDate: date.optional().or(z.literal("")), documentId: z.string().regex(/^[A-Za-z0-9_-]{1,191}$/).optional().or(z.literal("")) }).superRefine((value, context) => { if (value.effectiveEnd && value.effectiveEnd < value.effectiveStart) context.addIssue({ code: "custom", path: ["effectiveEnd"], message: "End date cannot precede the effective date." }); if (value.targetLow && value.targetHigh && Number(value.targetLow) > Number(value.targetHigh)) context.addIssue({ code: "custom", path: ["targetHigh"], message: "The range high value cannot be below its low value." }); });
const noon = (value: string) => new Date(`${value}T12:00:00.000Z`);
export async function createAuthenticatedCompensationWorkpaper(_previous: CompensationActionState, formData: FormData): Promise<CompensationActionState> { try { const context = await requireBusinessContext(); if (context.membership.role !== "OWNER") return { status: "error", message: "Only the business owner can add a compensation workpaper." }; const parsed = schema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { status: "error", message: parsed.error.issues[0]?.message ?? "Workpaper input is invalid." }; const data = parsed.data; const document = data.documentId ? await prisma.document.findFirst({ where: { id: data.documentId, businessId: context.business.id, status: "ACTIVE", malwareScanStatus: "CLEAN" }, select: { id: true } }) : null; if (data.documentId && !document) return { status: "error", message: "The selected evidence is unavailable." }; const workpaper = await prisma.reasonableCompWorkpaper.create({ data: { businessId: context.business.id, effectiveStart: noon(data.effectiveStart), effectiveEnd: data.effectiveEnd ? noon(data.effectiveEnd) : null, targetLow: data.targetLow || null, targetHigh: data.targetHigh || null, supportingNotes: data.supportingNotes, reviewDate: data.reviewDate ? noon(data.reviewDate) : null, documentId: document?.id } }); await prisma.auditEvent.create({ data: { actorType: "USER", businessId: context.business.id, actorMembershipId: context.user.id, action: "CREATE", entityType: "ReasonableCompWorkpaper", entityId: workpaper.id, afterJson: { effectiveStart: data.effectiveStart, hasRange: Boolean(data.targetLow || data.targetHigh), reviewDate: data.reviewDate || null }, metadataJson: { executionMode: "authenticated", taxConclusion: "none" } } }); revalidatePath("/app/taxes/owner-compensation"); return { status: "success", message: "Compensation workpaper saved for owner/CPA review; no compliance conclusion was made." }; } catch { return { status: "error", message: "The compensation workpaper could not be saved safely." }; } }
