"use server";

import { revalidatePath } from "next/cache";
import { requireBusinessMutationContext as requireBusinessContext } from "@/lib/security/business-context";
import { confirmTransactionImport, createImportPreview, ignoreExternalTransaction, postExternalTransaction } from "@/lib/services/financial-ingestion";

type Preview = Extract<Awaited<ReturnType<typeof createImportPreview>>, { ok: true }>["preview"];
type State = { ok: boolean; message?: string; preview?: Preview };
const mapping = (form: FormData) => { try { return JSON.parse(String(form.get("mapping") ?? "")); } catch { return undefined; } };

export async function previewImport(_: State, form: FormData): Promise<State> { try { const c = await requireBusinessContext(); const result = await createImportPreview({ businessId: c.business.id, actorUserId: c.user.id, role: c.membership.role }, { financialAccountId: String(form.get("financialAccountId") ?? ""), sourceFilename: String(form.get("sourceFilename") ?? ""), csvText: String(form.get("csvText") ?? ""), mapping: mapping(form), profileId: String(form.get("profileId") ?? "") }); return result.ok ? { ok: true, preview: result.preview, message: "Preview ready. Confirm only after reviewing new, duplicate, and invalid activity." } : { ok: false, message: result.message }; } catch { return { ok: false, message: "The import preview could not be authorized." }; } }
export async function confirmImport(_: State, form: FormData): Promise<State> { try { const c = await requireBusinessContext(); const result = await confirmTransactionImport({ businessId: c.business.id, actorUserId: c.user.id, role: c.membership.role }, { importId: String(form.get("importId") ?? ""), csvText: String(form.get("csvText") ?? ""), mapping: mapping(form), saveProfileName: String(form.get("saveProfileName") ?? "") }); if (!result.ok) return { ok: false, message: result.message }; revalidatePath("/app/money/import"); revalidatePath("/app/money"); revalidatePath("/app/today"); revalidatePath("/app/review"); return { ok: true, message: `${result.created} activity row${result.created === 1 ? "" : "s"} imported for review.` }; } catch { return { ok: false, message: "The import could not be authorized." }; } }
export async function postImportedTransaction(_: State, form: FormData): Promise<State> { try { const c = await requireBusinessContext(); const result = await postExternalTransaction({ businessId: c.business.id, actorUserId: c.user.id, role: c.membership.role }, { externalTransactionId: String(form.get("externalTransactionId") ?? ""), ledgerAccountId: String(form.get("ledgerAccountId") ?? ""), createRule: String(form.get("createRule") ?? "") === "true" }); if (!result.ok) return { ok: false, message: result.message }; revalidatePath("/app/money/import"); revalidatePath("/app/money"); revalidatePath("/app/today"); revalidatePath("/app/review"); return { ok: true, message: "Transaction posted to the balanced journal." }; } catch { return { ok: false, message: "The transaction could not be authorized." }; } }
export async function ignoreImportedTransaction(_: State, form: FormData): Promise<State> { try { const c = await requireBusinessContext(); const ok = await ignoreExternalTransaction({ businessId: c.business.id, actorUserId: c.user.id, role: c.membership.role }, String(form.get("externalTransactionId") ?? "")); if (!ok) return { ok: false, message: "This imported activity could not be excluded safely." }; revalidatePath("/app/money/import"); revalidatePath("/app/today"); revalidatePath("/app/review"); return { ok: true, message: "Imported activity was excluded without changing the ledger." }; } catch { return { ok: false, message: "The request could not be authorized." }; } }
