Foreground true
LocalSocket /run/clamav/clamd.ctl
LocalSocketMode 660
User clamav
StreamMaxLength 10485760
MaxFileSize 10485760
MaxScanSize 10485760
MaxThreads 1
ReadTimeout 30
CommandReadTimeout 30
LogTime false
LogClean false
