import { randomUUID } from "node:crypto";
import { config } from "dotenv";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createPrismaClient } from "../../src/lib/database/create-prisma-client";
import { reviewExtractionCandidate, runExtraction } from "../../src/lib/documents/extraction-core";

config({ path: ".env.test.local", override: false });
const url = process.env.TEST_DATABASE_URL?.trim(); if (!url) throw new Error("TEST_DATABASE_URL is not configured.");
const prisma = createPrismaClient(url); const run = randomUUID();
const ids = { user: `extract-user-${run}`, a: `extract-business-a-${run}`, b: `extract-business-b-${run}`, accountA: `extract-account-a-${run}`, accountB: `extract-account-b-${run}`, transaction: `extract-transaction-${run}`, document: `extract-document-${run}`, pending: `extract-pending-${run}`, other: `extract-other-${run}` };
const actor = { businessId: ids.a, actorUserId: ids.user };
const provider = { id: "test-fictional", version: "1", async extract() { return { ok: true as const, pageCount: 1, fields: [{ fieldType: "TOTAL_AMOUNT" as const, originalValue: "12.34", normalizedValue: "12.34", confidence: "0.9000" }, { fieldType: "DOCUMENT_DATE" as const, originalValue: "2026-07-05", normalizedValue: "2026-07-05", confidence: "0.8000" }] }; } };
function document(id: string, businessId: string, suffix: string, active = true) { return { id, businessId, uploadedByMembershipId: ids.user, storageKey: `extract-${suffix}`, originalFilename: `fictional-${suffix}.pdf`, displayName: `Fictional receipt ${suffix}`, mimeType: "application/pdf", sizeBytes: BigInt(12), storedSizeBytes: BigInt(12), sha256: suffix.repeat(64), type: "RECEIPT" as const, category: "RECEIPT" as const, status: active ? "ACTIVE" as const : "PENDING_VALIDATION" as const, storageState: active ? "STORED_PRIVATE" as const : "PENDING_STORAGE" as const, storageProvider: "LOCAL_FICTIONAL", malwareScanStatus: active ? "CLEAN" as const : "PENDING" as const, privateReadEligible: active, retentionClass: "GENERAL_TAX_SEVEN_YEARS" as const, retentionUntil: new Date("2033-01-01") }; }
describe("document extraction PostgreSQL integrity", () => {
  beforeAll(async () => { await prisma.user.create({ data: { id: ids.user, email: `extract-${run}@capturetracker.local`, displayName: "Extraction fixture", emailVerified: true } }); await prisma.business.createMany({ data: [{ id: ids.a, legalName: "Extract A LLC", displayName: "Extract A" }, { id: ids.b, legalName: "Extract B LLC", displayName: "Extract B" }] }); await prisma.businessMember.createMany({ data: [{ id: `extract-member-a-${run}`, businessId: ids.a, userId: ids.user, role: "OWNER" }, { id: `extract-member-b-${run}`, businessId: ids.b, userId: ids.user, role: "OWNER" }] }); await prisma.financialAccount.createMany({ data: [{ id: ids.accountA, businessId: ids.a, name: "Extract checking", type: "CHECKING", ownership: "BUSINESS", openingBalance: "0" }, { id: ids.accountB, businessId: ids.b, name: "Other checking", type: "CHECKING", ownership: "BUSINESS", openingBalance: "0" }] }); await prisma.transaction.create({ data: { id: ids.transaction, businessId: ids.a, accountId: ids.accountA, postedAt: new Date(), description: "Unchanged by extraction", amount: "12.34", direction: "OUTFLOW", sourceReference: `extract-${run}` } }); await prisma.document.createMany({ data: [document(ids.document, ids.a, "a"), document(ids.pending, ids.a, "b", false), document(ids.other, ids.b, "c")] }); });
  afterAll(async () => { await prisma.documentExtractionHistory.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.documentExtractionCandidate.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.documentExtractionAttempt.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.document.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.transaction.deleteMany({ where: { id: ids.transaction } }); await prisma.financialAccount.deleteMany({ where: { id: { in: [ids.accountA, ids.accountB] } } }); await prisma.businessMember.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.business.deleteMany({ where: { id: { in: [ids.a, ids.b] } } }); await prisma.user.deleteMany({ where: { id: ids.user } }); await prisma.$disconnect(); });
  it("enforces scoped eligibility and one canonical concurrent attempt", async () => { await expect(runExtraction(prisma, async () => new Uint8Array([1]), provider, actor, ids.other)).resolves.toMatchObject({ ok: false, code: "NOT_FOUND" }); await expect(runExtraction(prisma, async () => new Uint8Array([1]), provider, actor, ids.pending)).resolves.toMatchObject({ ok: false, code: "INELIGIBLE" }); await Promise.all(Array.from({ length: 6 }, () => runExtraction(prisma, async () => new Uint8Array([1]), provider, actor, ids.document))); expect(await prisma.documentExtractionAttempt.count({ where: { businessId: ids.a, documentId: ids.document } })).toBe(1); const attempt = await prisma.documentExtractionAttempt.findFirstOrThrow({ where: { businessId: ids.a, documentId: ids.document }, include: { candidates: true, history: true } }); expect(attempt.candidates).toHaveLength(2); expect(attempt.history.filter((event) => event.action === "REQUESTED")).toHaveLength(1); });
  it("keeps review history immutable, rejects stale evidence, and never changes accounting", async () => { const attempt = await prisma.documentExtractionAttempt.findFirstOrThrow({ where: { businessId: ids.a, documentId: ids.document }, include: { candidates: true } }); const total = attempt.candidates.find((candidate) => candidate.fieldType === "TOTAL_AMOUNT")!; const date = attempt.candidates.find((candidate) => candidate.fieldType === "DOCUMENT_DATE")!; const before = await prisma.transaction.findUniqueOrThrow({ where: { id: ids.transaction } }); await expect(reviewExtractionCandidate(prisma, actor, total.id, "ACCEPTED")).resolves.toMatchObject({ ok: true, state: "ACCEPTED" }); await expect(reviewExtractionCandidate(prisma, actor, date.id, "CORRECTED", "2026-07-06")).resolves.toMatchObject({ ok: true, state: "CORRECTED" }); expect(await prisma.documentExtractionHistory.count({ where: { businessId: ids.a, action: { in: ["ACCEPTED", "CORRECTED"] } } })).toBe(2); await prisma.document.update({ where: { id: ids.document }, data: { sha256: "d".repeat(64) } }); await expect(reviewExtractionCandidate(prisma, actor, total.id, "REJECTED")).resolves.toMatchObject({ ok: false, code: "STALE" }); const after = await prisma.transaction.findUniqueOrThrow({ where: { id: ids.transaction } }); expect(after).toMatchObject({ amount: before.amount, version: before.version, status: before.status }); });
});
