import { randomUUID } from "node:crypto";
import { config } from "dotenv";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createPrismaClient } from "../../src/lib/database/create-prisma-client";
import { decideTransactionMatch, dismissTransactionMatchRun, generateTransactionMatches } from "../../src/lib/documents/transaction-matching-core";

config({ path: ".env.test.local", override: false });
const url = process.env.TEST_DATABASE_URL?.trim(); if (!url) throw new Error("TEST_DATABASE_URL is not configured.");
const prisma = createPrismaClient(url); const run = randomUUID();
const ids = { user: `match-user-${run}`, a: `match-a-${run}`, b: `match-b-${run}`, accountA: `match-account-a-${run}`, accountB: `match-account-b-${run}`, document: `match-document-${run}`, staleDocument: `match-stale-document-${run}`, pending: `match-pending-${run}`, other: `match-other-${run}`, exact: `match-exact-${run}`, near: `match-near-${run}`, staleTransaction: `match-stale-transaction-${run}`, otherTransaction: `match-other-transaction-${run}` };
const actor = { businessId: ids.a, actorUserId: ids.user };
function document(id: string, businessId: string, suffix: string, active = true) { return { id, businessId, uploadedByMembershipId: ids.user, storageKey: `match-object-${suffix}-${run}`, originalFilename: `fictional-${suffix}.pdf`, displayName: `Fictional ${suffix}`, mimeType: "application/pdf", sizeBytes: BigInt(16), storedSizeBytes: BigInt(16), sha256: suffix.repeat(64), type: "RECEIPT" as const, category: "RECEIPT" as const, status: active ? "ACTIVE" as const : "PENDING_VALIDATION" as const, storageState: active ? "STORED_PRIVATE" as const : "PENDING_STORAGE" as const, storageProvider: "LOCAL_FICTIONAL", malwareScanStatus: active ? "CLEAN" as const : "PENDING" as const, privateReadEligible: active, documentDate: new Date("2026-07-10T00:00:00.000Z"), retentionClass: "GENERAL_TAX_SEVEN_YEARS" as const, retentionUntil: new Date("2033-01-01") }; }
async function reviewedAttempt(documentId: string, sha256: string, suffix: string) { return prisma.documentExtractionAttempt.create({ data: { id: `match-attempt-${suffix}-${run}`, businessId: ids.a, documentId, sourceSha256: sha256, sourceObjectVersion: null, adapterId: "test", adapterVersion: "1", status: "COMPLETED", requestedByUserId: ids.user, completedAt: new Date(), candidates: { create: [{ fieldType: "TOTAL_AMOUNT", originalValue: "12.34", normalizedValue: "12.34", confidence: "0.9", reviewState: "ACCEPTED", reviewedByUserId: ids.user, reviewedAt: new Date() }, { fieldType: "DOCUMENT_DATE", originalValue: "2026-07-10", normalizedValue: "2026-07-10", confidence: "0.9", reviewState: "ACCEPTED", reviewedByUserId: ids.user, reviewedAt: new Date() }, { fieldType: "MERCHANT_NAME", originalValue: "Fictional Office", normalizedValue: "Fictional Office", confidence: "0.9", reviewState: "ACCEPTED", reviewedByUserId: ids.user, reviewedAt: new Date() }, { fieldType: "CURRENCY", originalValue: "USD", normalizedValue: "USD", confidence: "0.9", reviewState: "ACCEPTED", reviewedByUserId: ids.user, reviewedAt: new Date() }] } } }); }

describe("document transaction matching PostgreSQL integrity", () => {
  beforeAll(async () => { await prisma.user.create({ data: { id: ids.user, email: `match-${run}@capturetracker.local`, displayName: "Matching fixture", emailVerified: true } }); await prisma.business.createMany({ data: [{ id: ids.a, legalName: "Match A LLC", displayName: "Match A" }, { id: ids.b, legalName: "Match B LLC", displayName: "Match B" }] }); await prisma.businessMember.createMany({ data: [{ id: `match-member-a-${run}`, businessId: ids.a, userId: ids.user, role: "OWNER" }, { id: `match-member-b-${run}`, businessId: ids.b, userId: ids.user, role: "OWNER" }] }); await prisma.financialAccount.createMany({ data: [{ id: ids.accountA, businessId: ids.a, name: "Match checking", type: "CHECKING", ownership: "BUSINESS", openingBalance: "0" }, { id: ids.accountB, businessId: ids.b, name: "Other checking", type: "CHECKING", ownership: "BUSINESS", openingBalance: "0" }] }); await prisma.transaction.createMany({ data: [{ id: ids.exact, businessId: ids.a, accountId: ids.accountA, postedAt: new Date("2026-07-10T00:00:00.000Z"), description: "Fictional Office supplies", merchantName: "Fictional Office", amount: "12.34", direction: "OUTFLOW", sourceReference: `match-exact-${run}` }, { id: ids.near, businessId: ids.a, accountId: ids.accountA, postedAt: new Date("2026-07-12T00:00:00.000Z"), description: "Fictional Office supplies", merchantName: "Fictional Office", amount: "12.34", direction: "OUTFLOW", sourceReference: `match-near-${run}` }, { id: ids.staleTransaction, businessId: ids.a, accountId: ids.accountA, postedAt: new Date("2026-07-10T00:00:00.000Z"), description: "Fictional Office stale", merchantName: "Fictional Office", amount: "12.34", direction: "OUTFLOW", sourceReference: `match-stale-${run}` }, { id: ids.otherTransaction, businessId: ids.b, accountId: ids.accountB, postedAt: new Date("2026-07-10T00:00:00.000Z"), description: "Foreign transaction", amount: "12.34", direction: "OUTFLOW", sourceReference: `match-other-${run}` }] }); await prisma.document.createMany({ data: [document(ids.document, ids.a, "a"), document(ids.staleDocument, ids.a, "b"), document(ids.pending, ids.a, "c", false), document(ids.other, ids.b, "d")] }); await reviewedAttempt(ids.document, "a".repeat(64), "a"); await reviewedAttempt(ids.staleDocument, "b".repeat(64), "b"); });
  afterAll(async () => { await prisma.documentMatchHistory.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.documentMatchSuggestion.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.documentMatchRun.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.transactionDocumentHistory.deleteMany({ where: { businessId: ids.a } }); await prisma.transactionDocument.deleteMany({ where: { businessId: ids.a } }); await prisma.documentExtractionHistory.deleteMany({ where: { businessId: ids.a } }); await prisma.documentExtractionCandidate.deleteMany({ where: { businessId: ids.a } }); await prisma.documentExtractionAttempt.deleteMany({ where: { businessId: ids.a } }); await prisma.document.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.transaction.deleteMany({ where: { id: { in: [ids.exact, ids.near, ids.staleTransaction, ids.otherTransaction] } } }); await prisma.financialAccount.deleteMany({ where: { id: { in: [ids.accountA, ids.accountB] } } }); await prisma.businessMember.deleteMany({ where: { businessId: { in: [ids.a, ids.b] } } }); await prisma.business.deleteMany({ where: { id: { in: [ids.a, ids.b] } } }); await prisma.user.deleteMany({ where: { id: ids.user } }); await prisma.$disconnect(); });
  it("scopes generation, is deterministic, and creates one canonical concurrent run", async () => { await expect(generateTransactionMatches(prisma, actor, ids.other)).resolves.toMatchObject({ ok: false, code: "INELIGIBLE" }); await expect(generateTransactionMatches(prisma, actor, ids.pending)).resolves.toMatchObject({ ok: false, code: "INELIGIBLE" }); const results = await Promise.all(Array.from({ length: 5 }, () => generateTransactionMatches(prisma, actor, ids.document))); expect(results.every((result) => result.ok)).toBe(true); const runs = await prisma.documentMatchRun.findMany({ where: { businessId: ids.a, documentId: ids.document }, include: { suggestions: { orderBy: { rank: "asc" } } } }); expect(runs).toHaveLength(1); expect(runs[0].suggestions.map((suggestion) => suggestion.transactionId)).not.toContain(ids.otherTransaction); expect(runs[0].suggestions[0]).toMatchObject({ transactionId: ids.exact, score: 95 }); expect(runs[0].suggestions[0].reasonCodes).toEqual(expect.arrayContaining(["EXACT_AMOUNT", "EXACT_DATE", "MERCHANT_MATCH", "CURRENCY_MATCH"])); });
  it("approves through one normal link idempotently without accounting changes", async () => { const suggestion = await prisma.documentMatchSuggestion.findFirstOrThrow({ where: { businessId: ids.a, transactionId: ids.exact }, include: { run: true } }); const before = await prisma.transaction.findUniqueOrThrow({ where: { id: ids.exact } }); const results = await Promise.all([decideTransactionMatch(prisma, actor, suggestion.id, "APPROVE"), decideTransactionMatch(prisma, actor, suggestion.id, "APPROVE")]); expect(results.some((result) => result.ok && result.state === "LINKED")).toBe(true); expect(await prisma.transactionDocument.count({ where: { businessId: ids.a, transactionId: ids.exact, documentId: ids.document, unlinkedAt: null } })).toBe(1); expect(await prisma.documentMatchHistory.count({ where: { businessId: ids.a, suggestionId: suggestion.id, action: "LINKED" } })).toBe(1); expect(await prisma.transaction.findUniqueOrThrow({ where: { id: ids.exact } })).toMatchObject({ amount: before.amount, postedAt: before.postedAt, version: before.version, status: before.status }); });
  it("rejects and dismisses immutably, and blocks changed transaction facts", async () => { const run = await prisma.documentMatchRun.findFirstOrThrow({ where: { businessId: ids.a, documentId: ids.document }, include: { suggestions: true } }); const rejected = run.suggestions.find((suggestion) => suggestion.transactionId === ids.near)!; await expect(decideTransactionMatch(prisma, actor, rejected.id, "REJECT")).resolves.toMatchObject({ ok: true, state: "REJECTED" }); await expect(dismissTransactionMatchRun(prisma, actor, run.id)).resolves.toMatchObject({ ok: true, state: "DISMISSED" }); expect(await prisma.documentMatchHistory.count({ where: { businessId: ids.a, runId: run.id, action: { in: ["REJECTED", "DISMISSED"] } } })).toBe(2); await expect(generateTransactionMatches(prisma, actor, ids.staleDocument)).resolves.toMatchObject({ ok: true }); const stale = await prisma.documentMatchSuggestion.findFirstOrThrow({ where: { businessId: ids.a, transactionId: ids.staleTransaction, run: { documentId: ids.staleDocument } } }); await prisma.transaction.update({ where: { id: ids.staleTransaction }, data: { amount: "13.34", version: { increment: 1 } } }); await expect(decideTransactionMatch(prisma, actor, stale.id, "APPROVE")).resolves.toMatchObject({ ok: false, code: "STALE" }); expect(await prisma.documentMatchHistory.count({ where: { businessId: ids.a, suggestionId: stale.id, action: "STALE" } })).toBe(1); });
});
