import { randomUUID } from "node:crypto";

import { config } from "dotenv";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { createPrismaClient } from "../../src/lib/database/create-prisma-client";
import { createManualTransaction } from "../../src/lib/services/manual-transaction";
import { correctPostedTransaction } from "../../src/lib/services/transaction-correction";
import { reverseJournalEntry } from "../../src/lib/services/journal-reversal";

config({ path: ".env.test.local", override: false });
const url = process.env.TEST_DATABASE_URL?.trim();
if (!url) throw new Error("TEST_DATABASE_URL is not configured.");
const prisma = createPrismaClient(url);
const run = randomUUID();
const ids = { owner: `correction-owner-${run}`, advisor: `correction-advisor-${run}`, business: `correction-business-${run}`, other: `correction-other-${run}`, account: `correction-account-${run}`, foreignAccount: `correction-foreign-account-${run}`, cash: `correction-cash-${run}`, income: `correction-income-${run}`, income2: `correction-income2-${run}`, expense: `correction-expense-${run}`, expense2: `correction-expense2-${run}`, contribution: `correction-contribution-${run}`, distribution: `correction-distribution-${run}`, period: `correction-period-${run}` };
const actor = { businessId: ids.business, actorUserId: ids.owner, actorMembershipId: `correction-member-${run}`, role: "OWNER" as const, executionMode: "authenticated" as const };
const key = (n: number) => `123e4567-e89b-42d3-a456-426614174${String(n).padStart(3, "0")}`;

const manual = (n: number, patch: Record<string, unknown> = {}) => createManualTransaction(prisma, actor, { transactionDate: "2026-08-10", amount: "100.00", merchantOrPayer: "Fictional counterparty", description: `Fictional transaction ${n}`, financialAccountId: ids.account, categoryAccountId: ids.income, transactionType: "INCOME", idempotencyKey: key(n), ...patch });
const correction = (transactionId: string, version: number, n: number, patch: Record<string, unknown> = {}) => correctPostedTransaction(prisma, actor, { transactionId, expectedVersion: String(version), correctionKey: key(100 + n), correctionReason: "Corrected fictional source facts", transactionDate: "2026-08-10", amount: "150.00", merchantOrPayer: "Corrected fictional counterparty", description: "Corrected fictional transaction", transactionType: "INCOME", categoryAccountId: ids.income, ...patch });
describe("posted transaction correction", () => {
  beforeAll(async () => {
    await prisma.user.createMany({ data: [{ id: ids.owner, email: `correction-owner-${run}@capturetracker.local`, displayName: "Correction owner" }, { id: ids.advisor, email: `correction-advisor-${run}@capturetracker.local`, displayName: "Correction advisor" }] });
    await prisma.business.createMany({ data: [{ id: ids.business, legalName: "Correction LLC", displayName: "Correction" }, { id: ids.other, legalName: "Other LLC", displayName: "Other" }] });
    await prisma.businessMember.createMany({ data: [{ id: actor.actorMembershipId, businessId: ids.business, userId: ids.owner, role: "OWNER" }, { id: `correction-advisor-member-${run}`, businessId: ids.business, userId: ids.advisor, role: "ADVISOR" }] });
    await prisma.financialAccount.createMany({ data: [{ id: ids.account, businessId: ids.business, name: "Correction Checking", type: "CHECKING", ownership: "BUSINESS" }, { id: ids.foreignAccount, businessId: ids.other, name: "Other Checking", type: "CHECKING", ownership: "BUSINESS" }] });
    await prisma.ledgerAccount.createMany({ data: [
      { id: ids.cash, businessId: ids.business, code: "1000", name: "Correction Checking", type: "ASSET", subtype: "BANK", normalBalance: "DEBIT", financialAccountId: ids.account },
      { id: ids.contribution, businessId: ids.business, code: "3000", name: "Owner Contributions", type: "EQUITY", subtype: "OWNER_CONTRIBUTION", normalBalance: "CREDIT" },
      { id: ids.distribution, businessId: ids.business, code: "3100", name: "Owner Distributions", type: "EQUITY", subtype: "OWNER_DISTRIBUTION", normalBalance: "DEBIT" },
      { id: ids.income, businessId: ids.business, code: "4000", name: "Fictional Income", type: "INCOME", subtype: "COMMISSION_INCOME", normalBalance: "CREDIT" },
      { id: ids.income2, businessId: ids.business, code: "4010", name: "Other Fictional Income", type: "INCOME", subtype: "OTHER_INCOME", normalBalance: "CREDIT" },
      { id: ids.expense, businessId: ids.business, code: "5900", name: "Fictional Expense", type: "EXPENSE", subtype: "OTHER_EXPENSE", normalBalance: "DEBIT" },
      { id: ids.expense2, businessId: ids.business, code: "5910", name: "Other Fictional Expense", type: "EXPENSE", subtype: "OTHER_EXPENSE", normalBalance: "DEBIT" },
    ] });
    await prisma.accountingPeriod.create({ data: { id: ids.period, businessId: ids.business, startsAt: new Date("2026-01-01T00:00:00.000Z"), endsAt: new Date("2026-12-31T23:59:59.999Z"), status: "OPEN" } });
  });

  afterAll(async () => { await prisma.$disconnect(); });

  it("preserves posted history, replaces the final accounting effect, links journals, and records audit history", async () => {
    const created = await manual(1); expect(created).toMatchObject({ ok: true, code: "CREATED" }); if (!created.ok) return;
    const before = await prisma.transaction.findUniqueOrThrow({ where: { id: created.transactionId }, include: { journalEntry: { include: { lines: { orderBy: { lineNumber: "asc" } } } } } });
    const result = await correction(created.transactionId, before.version, 1); expect(result).toMatchObject({ ok: true, code: "CORRECTED" }); if (!result.ok) return;
    const [original, replacement, reversal, replacementJournal] = await Promise.all([
      prisma.transaction.findUniqueOrThrow({ where: { id: created.transactionId }, include: { journalEntry: { include: { lines: { orderBy: { lineNumber: "asc" } } } } } }),
      prisma.transaction.findUniqueOrThrow({ where: { id: result.transactionId }, include: { splits: true, journalEntry: { include: { lines: true } } } }),
      prisma.journalEntry.findUniqueOrThrow({ where: { id: result.reversalJournalEntryId }, include: { lines: { orderBy: { lineNumber: "asc" } } } }),
      prisma.journalEntry.findUniqueOrThrow({ where: { id: result.replacementJournalEntryId }, include: { lines: true } }),
    ]);
    expect(original).toMatchObject({ status: "CORRECTED", description: "Fictional transaction 1", correctionReversalJournalId: reversal.id }); expect(original.amount.toFixed(2)).toBe("100.00"); expect(original.journalEntry?.lines.map((line) => [line.debitAmount.toFixed(2), line.creditAmount.toFixed(2)])).toEqual(before.journalEntry?.lines.map((line) => [line.debitAmount.toFixed(2), line.creditAmount.toFixed(2)]));
    expect(replacement).toMatchObject({ correctionOfId: original.id, status: "APPROVED" }); expect(replacement.amount.toFixed(2)).toBe("150.00"); expect(reversal.reversalOfEntryId).toBe(original.journalEntry?.id); expect(reversal.lines.map((line) => [line.debitAmount.toFixed(2), line.creditAmount.toFixed(2)])).toEqual(before.journalEntry?.lines.map((line) => [line.creditAmount.toFixed(2), line.debitAmount.toFixed(2)]));
    for (const journal of [reversal, replacementJournal]) expect(journal.lines.reduce((sum, line) => sum.plus(line.debitAmount), replacement.amount.minus(replacement.amount)).equals(journal.lines.reduce((sum, line) => sum.plus(line.creditAmount), replacement.amount.minus(replacement.amount)))).toBe(true);
    const reportLines = await prisma.journalLine.findMany({ where: { businessId: ids.business, journalEntry: { status: "POSTED", entryDate: { gte: new Date("2026-08-01T00:00:00.000Z"), lte: new Date("2026-08-31T23:59:59.999Z") } } }, include: { ledgerAccount: true } }); const zero = replacement.amount.minus(replacement.amount); const incomeEffect = reportLines.filter((line) => line.ledgerAccount.type === "INCOME").reduce((sum, line) => sum.plus(line.creditAmount).minus(line.debitAmount), zero); const cashEffect = reportLines.filter((line) => line.ledgerAccountId === ids.cash).reduce((sum, line) => sum.plus(line.debitAmount).minus(line.creditAmount), zero); const debit = reportLines.reduce((sum, line) => sum.plus(line.debitAmount), zero); const credit = reportLines.reduce((sum, line) => sum.plus(line.creditAmount), zero); expect(incomeEffect.toFixed(2)).toBe("150.00"); expect(cashEffect.toFixed(2)).toBe("150.00"); expect(debit.equals(credit)).toBe(true);
    const history = await prisma.auditEvent.findMany({ where: { businessId: ids.business, entityId: { in: [original.id, replacement.id] }, reason: { not: null } }, orderBy: { occurredAt: "asc" } }); expect(history).toHaveLength(2); expect(history.map((event) => event.action)).toEqual(["SUPERSEDE", "CREATE"]); expect(history[0]?.reason).toBe("Corrected fictional source facts");
    await expect(correction(original.id, original.version + 1, 1)).resolves.toMatchObject({ ok: true, code: "ALREADY_CORRECTED", transactionId: replacement.id }); await expect(correction(original.id, original.version + 1, 2)).resolves.toMatchObject({ ok: false, code: "CONFLICT" });
  });

  it("supports category, classification, mixed split, and personal-equity corrections", async () => {
    const expense = await manual(2, { transactionType: "BUSINESS_EXPENSE", categoryAccountId: ids.expense }); if (!expense.ok) throw new Error("fixture"); const expenseVersion = (await prisma.transaction.findUniqueOrThrow({ where: { id: expense.transactionId } })).version; const category = await correction(expense.transactionId, expenseVersion, 3, { transactionType: "BUSINESS_EXPENSE", categoryAccountId: ids.expense2, amount: "80.25" }); expect(category).toMatchObject({ ok: true });
    const classification = await manual(3, { transactionType: "BUSINESS_EXPENSE", categoryAccountId: ids.expense }); if (!classification.ok) throw new Error("fixture"); const classificationVersion = (await prisma.transaction.findUniqueOrThrow({ where: { id: classification.transactionId } })).version; const classified = await correction(classification.transactionId, classificationVersion, 4, { transactionType: "INCOME", categoryAccountId: ids.income2, amount: "55.00" }); expect(classified).toMatchObject({ ok: true }); if (classified.ok) { const replacement = await prisma.transaction.findUniqueOrThrow({ where: { id: classified.transactionId } }); expect(replacement).toMatchObject({ intent: "BUSINESS", direction: "INFLOW" }); expect(replacement.amount.toFixed(2)).toBe("55.00"); }
    const mixed = await manual(4, { transactionType: "MIXED", cashDirection: "OUTFLOW", categoryAccountId: ids.expense, businessAmount: "60.10", personalAmount: "39.90" }); if (!mixed.ok) throw new Error("fixture"); const mixedVersion = (await prisma.transaction.findUniqueOrThrow({ where: { id: mixed.transactionId } })).version; const mixedCorrected = await correction(mixed.transactionId, mixedVersion, 5, { transactionType: "MIXED", cashDirection: "OUTFLOW", categoryAccountId: ids.expense2, amount: "101.00", businessAmount: "60.55", personalAmount: "40.45" }); expect(mixedCorrected).toMatchObject({ ok: true }); if (mixedCorrected.ok) { const replacement = await prisma.transaction.findUniqueOrThrow({ where: { id: mixedCorrected.transactionId }, include: { splits: true, journalEntry: { include: { lines: true } } } }); expect(replacement.splits.map((split) => split.amount.toFixed(2)).sort()).toEqual(["40.45", "60.55"]); expect(replacement.journalEntry?.lines.some((line) => line.ledgerAccountId === ids.distribution && line.debitAmount.toFixed(2) === "40.45")).toBe(true); expect(replacement.journalEntry?.lines.some((line) => line.ledgerAccountId === ids.expense2 && line.debitAmount.toFixed(2) === "60.55")).toBe(true); }
    const personal = await manual(5, { transactionType: "PERSONAL", cashDirection: "OUTFLOW", categoryAccountId: undefined }); if (!personal.ok) throw new Error("fixture"); const personalVersion = (await prisma.transaction.findUniqueOrThrow({ where: { id: personal.transactionId } })).version; const personalCorrected = await correction(personal.transactionId, personalVersion, 6, { transactionType: "PERSONAL", cashDirection: "OUTFLOW", categoryAccountId: undefined, amount: "44.00" }); expect(personalCorrected).toMatchObject({ ok: true }); if (personalCorrected.ok) { const journal = await prisma.journalEntry.findUniqueOrThrow({ where: { id: personalCorrected.replacementJournalEntryId }, include: { lines: true } }); expect(journal.lines.some((line) => line.ledgerAccountId === ids.distribution)).toBe(true); expect(journal.lines.some((line) => [ids.expense, ids.expense2].includes(line.ledgerAccountId))).toBe(false); }
  });

  it("rejects stale, reversed, locked-period, unauthorized, and cross-business correction attempts", async () => {
    const created = await manual(6); if (!created.ok) throw new Error("fixture"); const original = await prisma.transaction.findUniqueOrThrow({ where: { id: created.transactionId }, include: { journalEntry: true } });
    await expect(correction(original.id, original.version + 1, 7)).resolves.toMatchObject({ ok: false, code: "CONFLICT" }); await expect(correction(original.id, original.version, 8, { transactionDate: "2027-01-01" })).resolves.toMatchObject({ ok: false, code: "NO_OPEN_PERIOD" }); await expect(correctPostedTransaction(prisma, { ...actor, role: "ADVISOR" }, { transactionId: original.id, expectedVersion: String(original.version), correctionKey: key(109), correctionReason: "No authority", transactionDate: "2026-08-10", amount: "150.00", merchantOrPayer: "Fictional", description: "Fictional", transactionType: "INCOME", categoryAccountId: ids.income })).resolves.toMatchObject({ ok: false, code: "FORBIDDEN" }); await expect(correctPostedTransaction(prisma, { ...actor, businessId: ids.other }, { transactionId: original.id, expectedVersion: String(original.version), correctionKey: key(110), correctionReason: "Foreign", transactionDate: "2026-08-10", amount: "150.00", merchantOrPayer: "Fictional", description: "Fictional", transactionType: "INCOME", categoryAccountId: ids.income })).resolves.toMatchObject({ ok: false, code: "NOT_FOUND" });
    const reversed = await manual(7); if (!reversed.ok) throw new Error("fixture"); const reverseTarget = await prisma.transaction.findUniqueOrThrow({ where: { id: reversed.transactionId }, include: { journalEntry: true } }); if (!reverseTarget.journalEntry) throw new Error("fixture"); await expect(reverseJournalEntry(prisma, actor, { journalEntryId: reverseTarget.journalEntry.id, expectedVersion: String(reverseTarget.journalEntry.version), reversalDate: "2026-08-10", reason: "Fictional reversal", confirmed: "on" })).resolves.toMatchObject({ ok: true }); await expect(correction(reversed.transactionId, reverseTarget.version, 11)).resolves.toMatchObject({ ok: false, code: "CONFLICT" });
  });
});
