ALTER TYPE "DocumentStorageState" ADD VALUE IF NOT EXISTS 'PENDING_STORAGE';
ALTER TYPE "DocumentStorageState" ADD VALUE IF NOT EXISTS 'STORED_PRIVATE';
ALTER TYPE "DocumentStorageState" ADD VALUE IF NOT EXISTS 'QUARANTINED_PRIVATE';
ALTER TYPE "DocumentStorageState" ADD VALUE IF NOT EXISTS 'STORAGE_FAILED';
