"use server";
import { revalidatePath } from "next/cache";
import type { OwnerMoneyActionState } from "@/components/owner-money-experience";
import { prisma } from "@/lib/prisma";
import { requireBusinessMutationContext as requireBusinessContext } from "@/lib/security/business-context";
import { createPersonallyPaidReimbursement } from "@/lib/services/reimbursement";
import { approveReimbursementClaim, matchReimbursementPayment } from "@/lib/services/reimbursement-settlement";
import { classifyOwnerTransfer } from "@/lib/services/owner-transfer";
import { postClassifiedOwnerTransfer } from "@/lib/services/owner-transfer";
export async function createAuthenticatedReimbursement(_previous: OwnerMoneyActionState, formData: FormData): Promise<OwnerMoneyActionState> {
  try { const context = await requireBusinessContext(); const result = await createPersonallyPaidReimbursement(prisma, { businessId: context.business.id, actorUserId: context.user.id, actorMembershipId: context.membership.id, role: context.membership.role, executionMode: "authenticated" }, Object.fromEntries(formData)); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/app/taxes/owner-money"); revalidatePath("/app/today"); revalidatePath("/app/review"); return { status: "success", message: result.code === "CREATED" ? "Reimbursement claim created for controlled review." : "This reimbursement claim was already recorded." }; } catch { return { status: "error", message: "The reimbursement could not be recorded safely. Refresh and try again." }; }
}
export async function classifyAuthenticatedOwnerTransfer(_previous: OwnerMoneyActionState, formData: FormData): Promise<OwnerMoneyActionState> { try { const context = await requireBusinessContext(); const actor = { businessId: context.business.id, actorUserId: context.user.id, actorMembershipId: context.membership.id, role: context.membership.role, executionMode: "authenticated" as const }; const input = Object.fromEntries(formData); const result = await classifyOwnerTransfer(prisma, actor, input); if (!result.ok) return { status: "error", message: result.message }; if (formData.get("postImmediately") === "on") { const posted = await postClassifiedOwnerTransfer(prisma, actor, input); if (!posted.ok) return { status: "error", message: posted.message }; revalidatePath("/app/money"); return { status: "success", message: "Explicit owner-transfer treatment posted as a balanced journal." }; } revalidatePath("/app/taxes/owner-money"); revalidatePath("/app/today"); revalidatePath("/app/review"); return { status: "success", message: "Owner transfer review recorded without posting accounting." }; } catch { return { status: "error", message: "The transfer review could not be saved safely." }; } }

const actorFromContext = async () => { const context = await requireBusinessContext(); return { businessId: context.business.id, actorUserId: context.user.id, actorMembershipId: context.membership.id, role: context.membership.role, executionMode: "authenticated" as const }; };
const refreshReimbursement = () => { revalidatePath("/app/taxes/owner-money"); revalidatePath("/app/today"); revalidatePath("/app/review"); revalidatePath("/app/money"); };
export async function approveAuthenticatedReimbursement(_previous: OwnerMoneyActionState, formData: FormData): Promise<OwnerMoneyActionState> { try { const result = await approveReimbursementClaim(prisma, await actorFromContext(), String(formData.get("claimId") ?? "")); if (!result.ok) return { status: "error", message: result.message }; refreshReimbursement(); return { status: "success", message: "Reimbursement due recorded as a balanced expense and payable journal." }; } catch { return { status: "error", message: "The reimbursement could not be approved safely." }; } }
export async function matchAuthenticatedReimbursementPayment(_previous: OwnerMoneyActionState, formData: FormData): Promise<OwnerMoneyActionState> { try { const result = await matchReimbursementPayment(prisma, await actorFromContext(), { claimId: String(formData.get("claimId") ?? ""), externalTransactionId: String(formData.get("externalTransactionId") ?? "") }); if (!result.ok) return { status: "error", message: result.message }; refreshReimbursement(); return { status: "success", message: "Exact bank evidence matched and reimbursement payable settled." }; } catch { return { status: "error", message: "The reimbursement payment could not be matched safely." }; } }
