import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { publicInvoice } from "@/lib/services/invoicing";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const metadata = { robots: { index: false, follow: false } };

export default async function PublicInvoicePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  if (!/^[A-Za-z0-9_-]{40,}$/.test(token)) notFound();
  const invoice = await publicInvoice(prisma, token); if (!invoice) notFound();
  const date = (value: Date | null) => value ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeZone: "UTC" }).format(value) : "Not issued";
  return <main className="min-h-screen bg-page px-4 py-8 text-text-primary sm:px-6"><article className="mx-auto max-w-3xl rounded-[var(--radius-lg)] border border-border-subtle bg-surface-primary p-6 shadow-sm sm:p-10"><header className="flex flex-wrap items-start justify-between gap-6 border-b border-border-subtle pb-6"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-brand-teal">Invoice</p><h1 className="mt-2 text-3xl font-bold text-brand-navy">{invoice.business.displayName}</h1><p className="mt-1 text-sm text-text-muted">{invoice.business.legalName}</p></div><div className="text-right"><p className="text-xl font-bold">{invoice.invoiceNumber}</p><p className="mt-1 text-sm text-text-muted">Issued {date(invoice.issueDate)}</p><p className="text-sm text-text-muted">Due {date(invoice.dueDate)}</p></div></header><section className="mt-6"><p className="text-sm font-bold text-text-muted">Bill to</p><p className="mt-1 font-bold">{invoice.customer.businessName}</p>{invoice.customer.contactName && <p className="text-sm">{invoice.customer.contactName}</p>}{invoice.customer.billingAddress && <p className="whitespace-pre-line text-sm">{invoice.customer.billingAddress}</p>}</section><section className="mt-8 overflow-x-auto"><table className="w-full min-w-[32rem] text-sm"><thead className="border-b border-border-subtle text-left text-text-muted"><tr><th className="pb-3">Service</th><th className="pb-3 text-right">Qty.</th><th className="pb-3 text-right">Rate</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.description} className="border-b border-border-subtle"><td className="py-4">{line.description}</td><td className="py-4 text-right">{line.quantity.toFixed(2)}</td><td className="money-value py-4 text-right">${line.rate.toFixed(2)}</td><td className="money-value py-4 text-right">${line.amount.toFixed(2)}</td></tr>)}</tbody><tfoot><tr><th className="pt-5 text-right text-base" colSpan={3}>Total</th><td className="money-value pt-5 text-right text-lg font-bold">${invoice.total.toFixed(2)}</td></tr></tfoot></table></section>{invoice.paymentInstructions && <section className="mt-8 rounded-[var(--radius-md)] bg-surface-secondary p-4"><h2 className="font-bold">Payment instructions</h2><p className="mt-2 whitespace-pre-line text-sm">{invoice.paymentInstructions}</p></section>}{invoice.terms && <section className="mt-6"><h2 className="font-bold">Terms</h2><p className="mt-2 whitespace-pre-line text-sm text-text-muted">{invoice.terms}</p></section>}{invoice.memo && <p className="mt-6 whitespace-pre-line text-sm text-text-muted">{invoice.memo}</p>}</article></main>;
}
