"use server";
import { revalidatePath } from "next/cache";
import type { OwnerMoneyActionState } from "@/components/owner-money-experience";
import { prisma } from "@/lib/prisma";
import { resolveLocalDemoContext } from "@/lib/security/local-demo-context";
import { createPersonallyPaidReimbursement } from "@/lib/services/reimbursement";
import { classifyOwnerTransfer } from "@/lib/services/owner-transfer";
import { approveReimbursementClaim, matchReimbursementPayment } from "@/lib/services/reimbursement-settlement";
export async function createDemoReimbursement(_previous: OwnerMoneyActionState, formData: FormData): Promise<OwnerMoneyActionState> { const context = await resolveLocalDemoContext(); if (!context) return { status: "error", message: "Local demo entry is unavailable." }; const result = await createPersonallyPaidReimbursement(prisma, { businessId: context.businessId, actorUserId: context.userId, actorMembershipId: context.membershipId, role: context.role, executionMode: "demo" }, Object.fromEntries(formData)); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/demo/taxes/owner-money"); revalidatePath("/demo/today"); revalidatePath("/demo/review"); return { status: "success", message: result.code === "CREATED" ? "Fictional reimbursement claim created for review." : "This reimbursement claim was already recorded." }; }
export async function classifyDemoOwnerTransfer(_previous: OwnerMoneyActionState, formData: FormData): Promise<OwnerMoneyActionState> { const context = await resolveLocalDemoContext(); if (!context) return { status: "error", message: "Local demo entry is unavailable." }; const result = await classifyOwnerTransfer(prisma, { businessId: context.businessId, actorUserId: context.userId, actorMembershipId: context.membershipId, role: context.role, executionMode: "demo" }, Object.fromEntries(formData)); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/demo/taxes/owner-money"); revalidatePath("/demo/today"); revalidatePath("/demo/review"); return { status: "success", message: "Fictional owner transfer review recorded without posting accounting." }; }
const demoActor = async () => { const context = await resolveLocalDemoContext(); return context ? { businessId: context.businessId, actorUserId: context.userId, actorMembershipId: context.membershipId, role: context.role, executionMode: "demo" as const } : null; };
export async function approveDemoReimbursement(_previous: OwnerMoneyActionState, formData: FormData): Promise<OwnerMoneyActionState> { const actor = await demoActor(); if (!actor) return { status: "error", message: "Local demo entry is unavailable." }; const result = await approveReimbursementClaim(prisma, actor, String(formData.get("claimId") ?? "")); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/demo/taxes/owner-money"); return { status: "success", message: "Fictional reimbursement approved." }; }
export async function matchDemoReimbursementPayment(_previous: OwnerMoneyActionState, formData: FormData): Promise<OwnerMoneyActionState> { const actor = await demoActor(); if (!actor) return { status: "error", message: "Local demo entry is unavailable." }; const result = await matchReimbursementPayment(prisma, actor, { claimId: String(formData.get("claimId") ?? ""), externalTransactionId: String(formData.get("externalTransactionId") ?? "") }); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/demo/taxes/owner-money"); return { status: "success", message: "Fictional reimbursement payment matched." }; }
