"use server";
import { revalidatePath } from "next/cache";
import { seedDemoDocuments, transitionDocument } from "@/lib/documents/service";
import { extractDocument, reviewDocumentExtraction } from "@/lib/documents/extraction";
import { decideDocumentTransactionMatch, dismissDocumentTransactionMatchRun, generateDocumentTransactionMatches } from "@/lib/documents/transaction-matching";
import { resolveLocalDemoContext } from "@/lib/security/local-demo-context";
import type { ExtractionActionState } from "@/app/app/documents/actions";
import type { DocumentMatchingActionState } from "@/app/app/documents/actions";
export async function createDemoDocuments() { const context = await resolveLocalDemoContext(); if (!context) return; await seedDemoDocuments({ businessId: context.businessId, actorUserId: context.userId }); revalidatePath("/demo/documents"); revalidatePath("/demo/today"); }
export async function transitionDemoDocument(documentId: string, status: "ACTIVE" | "QUARANTINED") { const context = await resolveLocalDemoContext(); if (!context) return; await transitionDocument({ businessId: context.businessId, actorUserId: context.userId }, documentId, status, status === "QUARANTINED" ? "SYNTHETIC_REVIEW" : undefined, "Synthetic metadata-only demo transition."); revalidatePath(`/demo/documents/${documentId}`); revalidatePath("/demo/today"); }
export async function runDemoExtraction(_: ExtractionActionState, formData: FormData): Promise<ExtractionActionState> { const context = await resolveLocalDemoContext(); const documentId = String(formData.get("documentId") ?? ""); if (!context || !documentId) return { ok: false, message: "Local demo extraction is unavailable." }; const result = await extractDocument({ businessId: context.businessId, actorUserId: context.userId }, documentId); if (!result.ok) return { ok: false, message: "Fictional extraction could not complete safely." }; revalidatePath(`/demo/documents/${documentId}`); revalidatePath("/demo/today"); return { ok: true, message: result.state === "EXISTING" ? "An extraction already exists." : "Fictional extraction completed." }; }
export async function reviewDemoExtraction(_: ExtractionActionState, formData: FormData): Promise<ExtractionActionState> { const context = await resolveLocalDemoContext(); const candidateId = String(formData.get("candidateId") ?? ""); const documentId = String(formData.get("documentId") ?? ""); const review = String(formData.get("review") ?? ""); if (!context || !candidateId || !documentId || !["ACCEPTED", "CORRECTED", "REJECTED"].includes(review)) return { ok: false, message: "Local demo review is invalid." }; const result = await reviewDocumentExtraction({ businessId: context.businessId, actorUserId: context.userId }, candidateId, review as "ACCEPTED" | "CORRECTED" | "REJECTED", String(formData.get("correctedValue") ?? "") || undefined); if (!result.ok) return { ok: false, message: "Extraction evidence could not be reviewed." }; revalidatePath(`/demo/documents/${documentId}`); revalidatePath("/demo/today"); return { ok: true, message: "Extraction evidence review saved." }; }
export async function runDemoDocumentMatching(_: DocumentMatchingActionState, formData: FormData): Promise<DocumentMatchingActionState> { const context = await resolveLocalDemoContext(); const documentId = String(formData.get("documentId") ?? ""); if (!context || !documentId) return { ok: false, message: "Local demo matching is unavailable." }; const result = await generateDocumentTransactionMatches({ businessId: context.businessId, actorUserId: context.userId }, documentId); if (!result.ok) return { ok: false, message: "Suggestions require current reviewed fictional evidence." }; revalidatePath(`/demo/documents/${documentId}`); revalidatePath("/demo/today"); return { ok: true, message: result.state === "EXISTING" ? "Current fictional suggestions already exist." : "Fictional suggestions are ready for review." }; }
export async function decideDemoDocumentMatching(_: DocumentMatchingActionState, formData: FormData): Promise<DocumentMatchingActionState> { const context = await resolveLocalDemoContext(); const documentId = String(formData.get("documentId") ?? ""); const suggestionId = String(formData.get("suggestionId") ?? ""); const decision = String(formData.get("decision") ?? ""); if (!context || !documentId || !suggestionId || !["APPROVE", "REJECT", "DISMISS"].includes(decision)) return { ok: false, message: "Local demo suggestion decision is invalid." }; const result = await decideDocumentTransactionMatch({ businessId: context.businessId, actorUserId: context.userId }, suggestionId, decision as "APPROVE" | "REJECT" | "DISMISS"); if (!result.ok) return { ok: false, message: "This fictional suggestion is stale or unavailable." }; revalidatePath(`/demo/documents/${documentId}`); revalidatePath("/demo/today"); return { ok: true, message: result.state === "LINKED" ? "Fictional document linked through the normal workflow." : "Fictional suggestion decision saved." }; }
export async function dismissDemoDocumentMatchingRun(_: DocumentMatchingActionState, formData: FormData): Promise<DocumentMatchingActionState> { const context = await resolveLocalDemoContext(); const documentId = String(formData.get("documentId") ?? ""); const runId = String(formData.get("runId") ?? ""); if (!context || !documentId || !runId) return { ok: false, message: "Local demo suggestion run is invalid." }; const result = await dismissDocumentTransactionMatchRun({ businessId: context.businessId, actorUserId: context.userId }, runId); if (!result.ok) return { ok: false, message: "Fictional suggestion run could not be dismissed." }; revalidatePath(`/demo/documents/${documentId}`); revalidatePath("/demo/today"); return { ok: true, message: "Fictional suggestion run dismissed." }; }
