"use server";
import { revalidatePath } from "next/cache";
import { seedDemoDocuments, transitionDocument } from "@/lib/documents/service";
import { extractDocument, reviewDocumentExtraction } from "@/lib/documents/extraction";
import { resolveLocalDemoContext } from "@/lib/security/local-demo-context";
import type { ExtractionActionState } from "@/app/app/documents/actions";
export async function createDemoDocuments() { const context = await resolveLocalDemoContext(); if (!context) return; await seedDemoDocuments({ businessId: context.businessId, actorUserId: context.userId }); revalidatePath("/demo/documents"); }
export async function transitionDemoDocument(documentId: string, status: "ACTIVE" | "QUARANTINED") { const context = await resolveLocalDemoContext(); if (!context) return; await transitionDocument({ businessId: context.businessId, actorUserId: context.userId }, documentId, status, status === "QUARANTINED" ? "SYNTHETIC_REVIEW" : undefined, "Synthetic metadata-only demo transition."); revalidatePath(`/demo/documents/${documentId}`); }
export async function runDemoExtraction(_: ExtractionActionState, formData: FormData): Promise<ExtractionActionState> { const context = await resolveLocalDemoContext(); const documentId = String(formData.get("documentId") ?? ""); if (!context || !documentId) return { ok: false, message: "Local demo extraction is unavailable." }; const result = await extractDocument({ businessId: context.businessId, actorUserId: context.userId }, documentId); if (!result.ok) return { ok: false, message: "Fictional extraction could not complete safely." }; revalidatePath(`/demo/documents/${documentId}`); return { ok: true, message: result.state === "EXISTING" ? "An extraction already exists." : "Fictional extraction completed." }; }
export async function reviewDemoExtraction(_: ExtractionActionState, formData: FormData): Promise<ExtractionActionState> { const context = await resolveLocalDemoContext(); const candidateId = String(formData.get("candidateId") ?? ""); const documentId = String(formData.get("documentId") ?? ""); const review = String(formData.get("review") ?? ""); if (!context || !candidateId || !documentId || !["ACCEPTED", "CORRECTED", "REJECTED"].includes(review)) return { ok: false, message: "Local demo review is invalid." }; const result = await reviewDocumentExtraction({ businessId: context.businessId, actorUserId: context.userId }, candidateId, review as "ACCEPTED" | "CORRECTED" | "REJECTED", String(formData.get("correctedValue") ?? "") || undefined); if (!result.ok) return { ok: false, message: "Extraction evidence could not be reviewed." }; revalidatePath(`/demo/documents/${documentId}`); return { ok: true, message: "Extraction evidence review saved." }; }
