"use server";
import { revalidatePath } from "next/cache";
import { finalizeReconciliationFromForm, saveReconciliationFromForm, type AccountingActionState } from "@/lib/services/reconciliation-action";
import { approveStatementActivityMatch, rejectStatementActivityCandidate, unmatchStatementActivity } from "@/lib/services/statement-activity-matching";
import { prisma } from "@/lib/prisma";
import { resolveLocalDemoContext } from "@/lib/security/local-demo-context";
const actor = async () => { const context = await resolveLocalDemoContext(); return context ? { businessId: context.businessId, actorUserId: context.userId, actorMembershipId: context.membershipId, role: context.role, executionMode: "demo" as const } : null; };
export async function saveDemoReconciliation(_state: AccountingActionState, form: FormData) { const context = await actor(); if (!context) return { status: "error" as const, message: "Local demo reconciliation is unavailable." }; const result = await saveReconciliationFromForm(context, form); if (result.status === "success") { revalidatePath("/demo/money/reconciliations"); revalidatePath("/demo/today"); } return result; }
export async function finalizeDemoReconciliation(_state: AccountingActionState, form: FormData) { const context = await actor(); if (!context) return { status: "error" as const, message: "Local demo reconciliation is unavailable." }; const result = await finalizeReconciliationFromForm(context, form); if (result.status === "success") { revalidatePath("/demo/money/reconciliations"); revalidatePath("/demo/today"); } return result; }
async function statement(action: typeof approveStatementActivityMatch, form: FormData) { const context=await actor(); if(!context)return {status:"error" as const,message:"Local demo reconciliation is unavailable."}; const result=await action(prisma,context,Object.fromEntries(form)); if(result.ok){revalidatePath("/demo/money/reconciliations");revalidatePath("/demo/today");return {status:"success" as const,message:`Statement activity ${result.state.toLowerCase()}.`};} return {status:result.code==="STALE"?"conflict" as const:"error" as const,message:"This statement activity changed. Refresh and try again."}; }
export async function matchDemoStatementActivity(_: AccountingActionState, form: FormData) { return statement(approveStatementActivityMatch,form); }
export async function rejectDemoStatementCandidate(_: AccountingActionState, form: FormData) { return statement(rejectStatementActivityCandidate,form); }
export async function unmatchDemoStatementActivity(_: AccountingActionState, form: FormData) { return statement(unmatchStatementActivity,form); }
