"use server";
import { revalidatePath } from "next/cache";
import { finalizeReconciliationFromForm, saveReconciliationFromForm, type AccountingActionState } from "@/lib/services/reconciliation-action";
import { approveStatementActivityMatch, rejectStatementActivityCandidate, unmatchStatementActivity } from "@/lib/services/statement-activity-matching";
import { prisma } from "@/lib/prisma";
import { requireBusinessContext } from "@/lib/security/business-context";
const actor = async () => { const context = await requireBusinessContext(); return { businessId: context.business.id, actorUserId: context.user.id, actorMembershipId: context.membership.id, role: context.membership.role, executionMode: "authenticated" as const }; };
export async function saveAuthenticatedReconciliation(_state: AccountingActionState, form: FormData) { try { const result = await saveReconciliationFromForm(await actor(), form); if (result.status === "success") { revalidatePath("/app/money/reconciliations"); revalidatePath("/app/today"); } return result; } catch { return { status: "error" as const, message: "Your reconciliation could not be authorized." }; } }
export async function finalizeAuthenticatedReconciliation(_state: AccountingActionState, form: FormData) { try { const result = await finalizeReconciliationFromForm(await actor(), form); if (result.status === "success") { revalidatePath("/app/money/reconciliations"); revalidatePath("/app/today"); } return result; } catch { return { status: "error" as const, message: "Your reconciliation could not be authorized." }; } }
async function statement(action: typeof approveStatementActivityMatch, form: FormData) { try { const result=await action(prisma,await actor(),Object.fromEntries(form)); if(result.ok){revalidatePath("/app/money/reconciliations");revalidatePath("/app/today");return {status:"success" as const,message:`Statement activity ${result.state.toLowerCase()}.`};} return {status:result.code==="STALE"?"conflict" as const:"error" as const,message:"This statement activity changed. Refresh and try again."}; } catch{return {status:"error" as const,message:"The statement activity could not be changed safely."};} }
export async function matchAuthenticatedStatementActivity(_: AccountingActionState, form: FormData) { return statement(approveStatementActivityMatch,form); }
export async function rejectAuthenticatedStatementCandidate(_: AccountingActionState, form: FormData) { return statement(rejectStatementActivityCandidate,form); }
export async function unmatchAuthenticatedStatementActivity(_: AccountingActionState, form: FormData) { return statement(unmatchStatementActivity,form); }
