"use client";

import Link from "next/link";
import { useActionState } from "react";
import { InlineAlert, PageHeader, StatusBadge } from "./ui";
import { PlaidLinkButton } from "./plaid-link-button";
import type { BankConnectionActionState } from "@/app/app/money/bank/actions";

type Action = (state: BankConnectionActionState, form: FormData) => Promise<BankConnectionActionState>;
type Props = {
  basePath?: "/app" | "/demo";
  liveProviderConfigured: boolean;
  canManage: boolean;
  accounts: Array<{ id: string; name: string; institutionName: string | null; type: string; lastFour: string | null; bankFeedMethod: "MANUAL" | "PLAID" }>;
  connections: Array<{ id: string; providerId: string; institutionName: string | null; state: string; lastAttemptedSyncAt: string | null; lastSuccessfulSyncAt: string | null; lastRun: { status: string; imported: number; duplicates: number; updated: number; removed: number; error: string | null } | null; accounts: Array<{ id: string; name: string; type: string; lastFour: string | null; isSelected: boolean; financialAccountId: string | null; financialAccountName: string | null }> }>;
  mapAction: Action; methodAction: Action; selectionAction: Action; syncAction: Action; disconnectAction: Action;
};
const initial: BankConnectionActionState = { ok: false };
const stamp = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not yet";
const tone = (state: string) => (state === "CONNECTED" || state === "COMPLETED" ? "success" : state === "SYNCING" ? "info" : "warning") as "success" | "info" | "warning";
const connectionLabel = (state: string) => state === "CONNECTED" ? "Connected" : state === "SYNCING" ? "Updating" : state === "DISCONNECTED" ? "Disconnected" : "Needs attention";

export function BankConnections({ basePath = "/app", liveProviderConfigured, canManage, accounts, connections, mapAction, methodAction, selectionAction, syncAction, disconnectAction }: Props) {
  const [mapState, map] = useActionState(mapAction, initial);
  const [methodState, chooseMethod] = useActionState(methodAction, initial);
  const [selectionState, chooseSelection] = useActionState(selectionAction, initial);
  const [syncState, sync] = useActionState(syncAction, initial);
  const [disconnectState, disconnect] = useActionState(disconnectAction, initial);
  const activePlaid = connections.filter((connection) => connection.providerId === "plaid" && connection.state !== "DISCONNECTED");
  const messages = [mapState, methodState, selectionState, syncState, disconnectState].filter((item) => item.message);

  return <section className="space-y-6">
    <PageHeader eyebrow="Money / bank" title="Bank connections" description="Choose Plaid or manual CSV for each business account. Both routes enter the same controlled review queue and never post automatically." action={<Link href={`${basePath}/money/import`} className="ui-button ui-button-secondary min-h-11 border border-border-subtle px-4 pt-3 text-sm font-bold">Import a transaction CSV</Link>}/>

    {!canManage && <InlineAlert title="Professional review" tone="info">This is read-only professional access. Connection, source, selection, and mapping decisions remain owner-only.</InlineAlert>}
    {!liveProviderConfigured && <InlineAlert title="Plaid is not configured" tone="warning">Live bank connection setup is unavailable. Manual transaction CSV import remains fully available for every business account.</InlineAlert>}

    <section className="ui-card p-5 sm:p-6">
      <div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand-teal">Bank activity setup</p><h2 className="mt-2 text-xl font-bold text-brand-navy">How would you like Capture Tracker to get your bank activity?</h2><p className="mt-2 text-sm leading-6 text-text-muted">You can change this later. Different accounts can use different methods. Switching preserves prior imports, reviews, and posted journal history.</p></div>
      <div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-[var(--radius-md)] border border-border-subtle p-4"><h3 className="font-bold text-brand-navy">Connect automatically</h3><p className="mt-2 text-sm leading-6 text-text-muted">Securely connect a bank or credit card and let Capture Tracker keep transaction activity synchronized.</p><p className="mt-3 text-xs font-bold text-brand-teal">Recommended for owners who want the least manual work.</p></div><div className="rounded-[var(--radius-md)] border border-border-subtle p-4"><h3 className="font-bold text-brand-navy">Import it myself</h3><p className="mt-2 text-sm leading-6 text-text-muted">Download transaction activity from the bank and upload it to Capture Tracker whenever desired.</p><p className="mt-3 text-xs font-bold text-brand-teal">Good for owners who prefer not to connect a financial institution.</p></div></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">{accounts.map((account) => <article key={account.id} className="rounded-[var(--radius-md)] border border-border-subtle bg-surface-secondary p-4">
        <div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-bold">{account.name}</h3><p className="mt-1 text-xs text-text-muted">{account.institutionName ?? account.type.replaceAll("_", " ").toLowerCase()}{account.lastFour ? ` · ending ${account.lastFour}` : ""}</p></div><StatusBadge tone={account.bankFeedMethod === "PLAID" ? "info" : "success"}>{account.bankFeedMethod === "PLAID" ? "Plaid" : "Manual CSV"}</StatusBadge></div>
        {canManage && <form action={chooseMethod} className="mt-4 grid grid-cols-1 gap-2 min-[390px]:grid-cols-2"><input type="hidden" name="financialAccountId" value={account.id}/><button name="method" value="PLAID" className={`ui-button min-h-11 border px-3 text-sm font-bold ${account.bankFeedMethod === "PLAID" ? "border-brand-teal bg-brand-teal-soft text-brand-navy" : "border-border-subtle bg-surface-secondary text-brand-navy"}`}>Connect bank</button><button name="method" value="MANUAL" className={`ui-button min-h-11 border px-3 text-sm font-bold ${account.bankFeedMethod === "MANUAL" ? "border-brand-teal bg-brand-teal-soft text-brand-navy" : "border-border-subtle bg-surface-secondary text-brand-navy"}`}>Import CSV</button></form>}
      </article>)}</div>
      {!accounts.length && <p className="mt-4 text-sm text-text-muted">Add an active business financial account before choosing an activity method.</p>}
    </section>

    <section className="ui-card p-5 sm:p-6"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand-teal">Read-only transaction access</p><h2 className="mt-2 text-xl font-bold text-brand-navy">Connect an institution with Plaid</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-text-muted">Plaid Link collects your institution consent. Capture Tracker never asks for bank credentials. Plaid shares selected account identity and transaction activity; Capture Tracker encrypts the access token and stores only the minimum evidence needed for review, audit, and deduplication. No Transfer, Auth, payment, or money-movement product is enabled.</p></div>{canManage && liveProviderConfigured && <PlaidLinkButton/>}</div></section>

    {activePlaid.length ? <div className="space-y-4">{activePlaid.map((connection) => <section key={connection.id} className="ui-card overflow-hidden">
      <div className="flex flex-col gap-4 border-b border-border-subtle p-5 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-bold">{connection.institutionName ?? "Financial institution"}</h2><p className="mt-1 text-sm text-text-muted">Last attempted: {stamp(connection.lastAttemptedSyncAt)} · Last successful: {stamp(connection.lastSuccessfulSyncAt)}</p></div><StatusBadge tone={tone(connection.state)}>{connectionLabel(connection.state)}</StatusBadge></div>
      <div className="divide-y divide-border-subtle">{connection.accounts.map((account) => <article key={account.id} className="grid min-w-0 gap-4 p-5 xl:grid-cols-[minmax(0,1fr)_minmax(18rem,auto)] xl:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{account.name}</p><StatusBadge tone={account.isSelected ? "success" : "warning"}>{account.isSelected ? "Selected" : "Paused"}</StatusBadge></div><p className="mt-1 text-sm text-text-muted">{account.type.replaceAll("_", " ").toLowerCase()}{account.lastFour ? ` · ending ${account.lastFour}` : ""}</p><p className="mt-2 text-sm text-text-muted">{account.financialAccountName ? `Mapped to ${account.financialAccountName}` : "Map this to one Capture Tracker business account before Plaid activity can enter review."}</p></div>{canManage && <div className="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><form action={map} className="contents"><input type="hidden" name="connectedAccountId" value={account.id}/><select name="financialAccountId" defaultValue={account.financialAccountId ?? ""} className="ui-input min-h-11 min-w-0"><option value="">No mapping</option>{accounts.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.name} · {candidate.bankFeedMethod === "PLAID" ? "Plaid" : "CSV"}</option>)}</select><button className="ui-button ui-button-secondary min-h-11 border border-border-subtle px-3 text-sm font-bold">Save mapping</button></form><form action={chooseSelection} className="sm:col-span-2"><input type="hidden" name="connectedAccountId" value={account.id}/><input type="hidden" name="selected" value={account.isSelected ? "false" : "true"}/><button className="min-h-11 text-sm font-bold text-brand-navy underline underline-offset-4">{account.isSelected ? "Pause this account" : "Resume this account"}</button></form></div>}</article>)}</div>
      {connection.lastRun && <p className="border-t border-border-subtle p-4 text-xs leading-5 text-text-muted">Last sync: {connection.lastRun.status.toLowerCase()} · {connection.lastRun.imported} new · {connection.lastRun.updated} updated · {connection.lastRun.removed} removed · {connection.lastRun.duplicates} duplicate{connection.lastRun.error ? ` · ${connection.lastRun.error}` : ""}</p>}
      {canManage && <div className="grid gap-4 border-t border-border-subtle bg-surface-secondary p-5 lg:grid-cols-[1fr_auto] lg:items-start"><div className="flex flex-col gap-3 sm:flex-row"><form action={sync}><input type="hidden" name="connectionId" value={connection.id}/><button className="ui-button ui-button-secondary min-h-11 w-full border border-border-subtle px-4 text-sm font-bold sm:w-auto">Sync now</button></form>{connection.state === "RECONNECT_REQUIRED" && liveProviderConfigured && <PlaidLinkButton connectionId={connection.id}/>}</div><form action={disconnect} className="grid gap-2 rounded-[var(--radius-sm)] border border-status-warning/40 bg-white p-3"><label className="flex items-start gap-2 text-xs leading-5 text-text-muted"><input required type="checkbox" name="confirmation" value="DISCONNECT" className="mt-1"/>Disconnect the entire Plaid Item. History stays; mapped accounts return to CSV.</label><input type="hidden" name="connectionId" value={connection.id}/><button className="ui-button min-h-11 border border-status-warning px-3 text-sm font-bold text-status-warning">Disconnect institution</button></form></div>}
    </section>)}</div> : <section className="ui-card p-6"><h2 className="font-bold">No active Plaid connections</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-text-muted">Nothing starts automatically. The owner may connect Plaid above, or keep using transaction CSV import account by account.</p></section>}

    <section className="ui-card p-5 sm:p-6"><h2 className="font-bold text-brand-navy">Plaid outage or access issue?</h2><p className="mt-2 text-sm leading-6 text-text-muted">Your imported and posted history remains available. Switch the affected Capture Tracker account to manual CSV, upload new activity, and use reconnect later. Do not create a second Item for the same bank.</p><Link href={`${basePath}/money/import`} className="mt-3 inline-flex min-h-11 items-center font-bold text-brand-navy underline underline-offset-4">Open transaction CSV import</Link></section>

    {messages.map((state, index) => <InlineAlert key={`${state.message}-${index}`} title={state.ok ? "Bank setting saved" : "Bank setting unavailable"} tone={state.ok ? "success" : "warning"}>{state.message}</InlineAlert>)}
  </section>;
}
