"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import type { BillActionState } from "@/app/app/money/bills/actions";
import { ButtonLink, Card, EmptyState, PageHeader, StatusBadge } from "./ui";

const initial: BillActionState = { status: "idle", message: null };
type Action = (state: BillActionState, form: FormData) => Promise<BillActionState>;
type Props = { vendors: Array<{ id: string; name: string }>; accounts: Array<{ id: string; name: string }>; financialAccounts: Array<{ id: string; name: string }>; bills: Array<{ id: string; vendor: string; billNumber: string | null; total: string; paid: string; dueDate: string | null; status: string }>; vendorAction: Action; billAction: Action; approveAction: Action; paymentAction: Action; canMutate?: boolean; initialOpen?: boolean };

export function BillCenter({ vendors, accounts, financialAccounts, bills, vendorAction, billAction, approveAction, paymentAction, canMutate = true, initialOpen = false }: Props) {
  const [vendor, saveVendor, vendorPending] = useActionState(vendorAction, initial); const [bill, saveBill, billPending] = useActionState(billAction, initial); const [approval, submitApproval] = useActionState(approveAction, initial); const [payment, submitPayment] = useActionState(paymentAction, initial); const [show, setShow] = useState(initialOpen && canMutate);
  return <>
    <PageHeader eyebrow="Pay what I owe" title="Bills" description="Record vendor obligations when they are incurred, track due dates, and match payment evidence later without counting the expense twice." action={canMutate ? <button className="ui-button ui-button-primary min-h-11 px-4" onClick={() => setShow(!show)}>{show ? "Hide forms" : "Add bill"}</button> : <StatusBadge tone="locked">Read-only professional review</StatusBadge>} />
    {show && canMutate ? <div className="mt-6 grid gap-6 lg:grid-cols-2"><form action={saveVendor} className="ui-card grid gap-3 p-5"><h2 className="font-bold">New vendor</h2><Field label="Vendor name"><input required className="ui-input mt-1" name="name" /></Field><Field label="Contact name"><input className="ui-input mt-1" name="contactName" /></Field><Field label="Email"><input className="ui-input mt-1" name="email" type="email" /></Field><Field label="Payment terms"><input className="ui-input mt-1" name="paymentTerms" placeholder="Net 30" /></Field>{vendor.message ? <p role={vendor.status === "error" ? "alert" : "status"} className="text-sm font-bold">{vendor.message}</p> : null}<button disabled={vendorPending} className="ui-button ui-button-secondary min-h-11 px-4">Save vendor</button></form><form action={saveBill} className="ui-card grid gap-3 p-5"><h2 className="font-bold">New bill</h2><Field label="Vendor"><select required className="ui-input mt-1" name="vendorId" defaultValue=""><option value="" disabled>Select vendor</option>{vendors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Expense or asset account"><select required className="ui-input mt-1" name="ledgerAccountId" defaultValue=""><option value="" disabled>Select account</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Description"><input required className="ui-input mt-1" name="description" /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Amount"><input required className="ui-input mt-1" name="amount" inputMode="decimal" /></Field><Field label="Bill number"><input className="ui-input mt-1" name="billNumber" /></Field><Field label="Bill date"><input required className="ui-input mt-1" name="billDate" type="date" /></Field><Field label="Due date"><input required className="ui-input mt-1" name="dueDate" type="date" /></Field></div>{bill.message ? <p role={bill.status === "error" ? "alert" : "status"} className="text-sm font-bold">{bill.message}</p> : null}<button disabled={billPending} className="ui-button ui-button-primary min-h-11 px-4">Create draft</button></form></div> : null}
    <Card className="mt-6 p-5"><h2 className="font-bold">Bill register</h2>{bills.length ? <div className="mt-3 space-y-3">{bills.map((item) => <section key={item.id} className="border-t border-border-subtle pt-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{item.vendor}{item.billNumber ? ` · ${item.billNumber}` : ""}</p><p className="money-value text-sm">${item.total} · ${item.paid} paid{item.dueDate ? ` · Due ${item.dueDate}` : ""}</p></div><div className="flex items-center gap-3"><StatusBadge tone={item.status === "PAID" ? "success" : "warning"}>{item.status.replaceAll("_", " ")}</StatusBadge>{canMutate && ["DRAFT", "REVIEW"].includes(item.status) ? <form action={submitApproval}><input type="hidden" name="billId" value={item.id}/><button className="ui-button ui-button-secondary min-h-10 px-3">Approve</button></form> : null}</div></div>{canMutate && ["APPROVED", "DUE", "PARTIALLY_PAID"].includes(item.status) ? <details className="mt-3"><summary className="cursor-pointer text-sm font-bold text-brand-navy">Record payment</summary><form action={submitPayment} className="mt-3 grid gap-3 sm:grid-cols-4"><input type="hidden" name="billId" value={item.id}/><Field label="Amount"><input required className="ui-input mt-1" name="amount" inputMode="decimal"/></Field><Field label="Paid"><input required className="ui-input mt-1" name="paidAt" type="date"/></Field><Field label="Payment account"><select className="ui-input mt-1" name="financialAccountId" defaultValue=""><option value="">Choose account</option>{financialAccounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="Reference"><input className="ui-input mt-1" name="reference" maxLength={500}/></Field><button className="ui-button ui-button-primary min-h-11 px-3 sm:col-span-4">Record owner-confirmed payment</button></form></details> : null}</section>)}</div> : <EmptyState title="No bills yet"><span>Add a vendor bill when the obligation is incurred. Later, match the outgoing payment without recording the expense a second time.</span>{canMutate ? <ButtonLink className="mt-4" href="/app/money/bills?new=bill">Add bill</ButtonLink> : null}</EmptyState>}{approval.message ? <p className="mt-4 text-sm font-bold">{approval.message}</p> : null}{payment.message ? <p className="mt-4 text-sm font-bold">{payment.message}</p> : null}<div className="mt-5 flex flex-wrap gap-4 border-t border-border-subtle pt-4 text-sm"><Link className="ui-link font-bold" href="/app/reports/operations?report=ap-aging">What do I owe? →</Link><Link className="ui-link font-bold" href="/app/money">Review possible vendor payments →</Link></div></Card>
  </>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-bold text-text-muted">{label}{children}</label>; }
