"use client";

import { useActionState, useState } from "react";
import { Card, PageHeader, StatusBadge } from "./ui";
import type { BillActionState } from "@/app/app/money/bills/actions";

const initial: BillActionState = { status: "idle", message: null };
type Action = (state: BillActionState, form: FormData) => Promise<BillActionState>;
export function BillCenter({ vendors, accounts, financialAccounts, bills, vendorAction, billAction, approveAction, paymentAction }: { vendors: Array<{ id: string; name: string }>; accounts: Array<{ id: string; name: string }>; financialAccounts: Array<{ id: string; name: string }>; bills: Array<{ id: string; vendor: string; billNumber: string | null; total: string; paid: string; dueDate: string | null; status: string }>; vendorAction: Action; billAction: Action; approveAction: Action; paymentAction: Action }) {
  const [vendor, saveVendor, vendorPending] = useActionState(vendorAction, initial); const [bill, saveBill, billPending] = useActionState(billAction, initial); const [approval, submitApproval] = useActionState(approveAction, initial); const [payment, submitPayment] = useActionState(paymentAction, initial); const [show, setShow] = useState(false);
  return <><PageHeader eyebrow="Money" title="Bills" description="Record vendor bills, payables, and owner-confirmed payments. Payment initiation is not included." action={<button className="ui-button ui-button-primary min-h-11 px-4" onClick={() => setShow(!show)}>{show ? "Hide forms" : "New bill"}</button>} />
    {show && <div className="mt-6 grid gap-6 lg:grid-cols-2"><form action={saveVendor} className="ui-card grid gap-3 p-5"><h2 className="font-bold">New vendor</h2><label className="text-sm font-bold text-text-muted">Vendor name<input required className="ui-input mt-1" name="name" /></label><label className="text-sm font-bold text-text-muted">Contact name<input className="ui-input mt-1" name="contactName" /></label><label className="text-sm font-bold text-text-muted">Email<input className="ui-input mt-1" name="email" type="email" /></label><label className="text-sm font-bold text-text-muted">Payment terms<input className="ui-input mt-1" name="paymentTerms" placeholder="Net 30" /></label>{vendor.message && <p className="text-sm font-bold">{vendor.message}</p>}<button disabled={vendorPending} className="ui-button ui-button-secondary min-h-11 px-4">Save vendor</button></form><form action={saveBill} className="ui-card grid gap-3 p-5"><h2 className="font-bold">New bill</h2><label className="text-sm font-bold text-text-muted">Vendor<select required className="ui-input mt-1" name="vendorId" defaultValue=""><option value="" disabled>Select vendor</option>{vendors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-bold text-text-muted">Expense or asset account<select required className="ui-input mt-1" name="ledgerAccountId" defaultValue=""><option value="" disabled>Select account</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-bold text-text-muted">Description<input required className="ui-input mt-1" name="description" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold text-text-muted">Amount<input required className="ui-input mt-1" name="amount" inputMode="decimal" /></label><label className="text-sm font-bold text-text-muted">Bill number<input className="ui-input mt-1" name="billNumber" /></label><label className="text-sm font-bold text-text-muted">Bill date<input required className="ui-input mt-1" name="billDate" type="date" /></label><label className="text-sm font-bold text-text-muted">Due date<input required className="ui-input mt-1" name="dueDate" type="date" /></label></div>{bill.message && <p className="text-sm font-bold">{bill.message}</p>}<button disabled={billPending} className="ui-button ui-button-primary min-h-11 px-4">Create draft</button></form></div>}
    <Card className="mt-6 p-5"><h2 className="font-bold">Bill register</h2>{bills.length ? <div className="mt-3 space-y-3">{bills.map((item) => <section key={item.id} className="border-t border-border-subtle pt-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{item.vendor}{item.billNumber ? ` · ${item.billNumber}` : ""}</p><p className="money-value text-sm">${item.total} · ${item.paid} paid{item.dueDate ? ` · Due ${item.dueDate}` : ""}</p></div><div className="flex items-center gap-3"><StatusBadge tone={item.status === "PAID" ? "success" : "warning"}>{item.status.replaceAll("_", " ")}</StatusBadge>{["DRAFT", "REVIEW"].includes(item.status) && <form action={submitApproval}><input type="hidden" name="billId" value={item.id}/><button className="ui-button ui-button-secondary min-h-10 px-3">Approve</button></form>}</div></div>{["APPROVED", "DUE", "PARTIALLY_PAID"].includes(item.status) && <details className="mt-3"><summary className="cursor-pointer text-sm font-bold text-brand-navy">Record payment</summary><form action={submitPayment} className="mt-3 grid gap-3 sm:grid-cols-4"><input type="hidden" name="billId" value={item.id}/><label className="text-sm font-bold text-text-muted">Amount<input required className="ui-input mt-1" name="amount" inputMode="decimal"/></label><label className="text-sm font-bold text-text-muted">Paid<input required className="ui-input mt-1" name="paidAt" type="date"/></label><label className="text-sm font-bold text-text-muted">Payment account<select className="ui-input mt-1" name="financialAccountId" defaultValue=""><option value="">Choose account</option>{financialAccounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="text-sm font-bold text-text-muted">Reference<input className="ui-input mt-1" name="reference" maxLength={500}/></label><button className="ui-button ui-button-primary min-h-11 px-3 sm:col-span-4">Record owner-confirmed payment</button></form></details>}</section>)}</div> : <p className="mt-3 text-sm text-text-muted">No bills recorded.</p>}{approval.message && <p className="mt-4 text-sm font-bold">{approval.message}</p>}{payment.message && <p className="mt-4 text-sm font-bold">{payment.message}</p>}</Card></>;
}
