"use client";

import { useActionState } from "react";
import { EmptyState, PageHeader } from "./ui";

type State = { message: string | null; link?: string; error?: boolean }; const initial: State = { message: null }; type Action = (state: State, form: FormData) => Promise<State>;
type Props = { documentAccess: boolean; invitations: Array<{ id: string; email: string; status: string; expiresAt: string }>; cpas: Array<{ id: string; email: string; name: string }>; invite: Action; revokeInvitation: Action; setDocumentAccess: Action; revokeAccess: Action };

export function CpaManagement({ documentAccess, invitations, cpas, invite, revokeInvitation, setDocumentAccess, revokeAccess }: Props) {
  const [invitation, inviteAction] = useActionState(invite, initial); const [policy, policyAction] = useActionState(setDocumentAccess, initial); const [revoke, revokeAction] = useActionState(revokeInvitation, initial); const [access, accessAction] = useActionState(revokeAccess, initial);
  return <section className="space-y-6"><PageHeader eyebrow="CPA / year-end" title="CPA access" description="Give your CPA secure read-only access for professional review. You remain in control of invitations and document visibility." />
    <section className="ui-card p-5"><h2 className="font-bold">Invite a CPA</h2><p className="mt-2 text-sm text-text-muted">CPA access cannot create, edit, approve, post, or delete business records. Email delivery is not configured, so copy the generated invitation link securely.</p><form action={inviteAction} className="mt-4 flex flex-wrap gap-3"><label className="min-w-0 flex-1 text-sm font-bold text-text-muted">CPA email<input className="ui-input mt-1 min-h-11" required name="email" type="email" placeholder="cpa@example.com"/></label><button className="ui-button ui-button-primary min-h-11 self-end px-4">Create invitation</button></form>{invitation.message ? <p role={invitation.error ? "alert" : "status"} className="mt-3 text-sm font-bold">{invitation.message}</p> : null}{invitation.link ? <input className="ui-input mt-3 w-full" readOnly value={invitation.link} aria-label="CPA invitation link"/> : null}</section>
    <section className="ui-card p-5"><h2 className="font-bold">CPA document access</h2><p className="mt-1 text-sm text-text-muted">Only ACTIVE + CLEAN documents are eligible when access is on. Pending, quarantined, rejected, or infected documents stay unavailable.</p><form action={policyAction} className="mt-3"><input type="hidden" name="enabled" value={String(!documentAccess)}/><button className="ui-button ui-button-secondary min-h-11 px-4">Turn document access {documentAccess ? "off" : "on"}</button></form>{policy.message ? <p className="mt-2 text-sm">{policy.message}</p> : null}</section>
    <section className="ui-card p-5"><h2 className="font-bold">Pending invitations</h2>{invitations.length ? invitations.map((item) => <div className="mt-3 flex flex-wrap items-center justify-between gap-3 border-t border-border-subtle pt-3" key={item.id}><span className="text-sm">{item.email} · {item.status}</span><form action={revokeAction}><input type="hidden" name="invitationId" value={item.id}/><button className="ui-button ui-button-secondary min-h-10 px-3">Revoke</button></form></div>) : <p className="mt-3 text-sm text-text-muted">No invitation is waiting for acceptance. Use the form above when your CPA is ready.</p>}{revoke.message ? <p className="mt-2 text-sm">{revoke.message}</p> : null}</section>
    <section className="ui-card p-5"><h2 className="font-bold">Accepted CPA access</h2>{cpas.length ? cpas.map((item) => <div className="mt-3 flex flex-wrap items-center justify-between gap-3 border-t border-border-subtle pt-3" key={item.id}><span className="text-sm">{item.name} · {item.email}</span><form action={accessAction}><input type="hidden" name="membershipId" value={item.id}/><button className="ui-button ui-button-secondary min-h-10 px-3">Revoke access</button></form></div>) : <EmptyState title="No CPA has access yet">Invite a CPA above to provide secure read-only review access. The CPA cannot perform owner actions or change the books.</EmptyState>}{access.message ? <p className="mt-2 text-sm">{access.message}</p> : null}</section>
  </section>;
}
