"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";

export function InvitationAccountForm({ token, businessDisplayName, email }: { token: string; businessDisplayName: string; email: string }) {
  const [message, setMessage] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setMessage(null); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/operator/invitations/account", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token, name: String(form.get("name") ?? ""), email: String(form.get("email") ?? ""), password: String(form.get("password") ?? ""), confirmPassword: String(form.get("confirmPassword") ?? "") }) }); if (response.ok) { setMessage("Account created. Sign in, then return to this invitation link to accept it."); return; } setMessage("Account creation could not be completed."); } catch { setMessage("Account creation could not be completed."); } finally { setSubmitting(false); } }
  return <main className="auth-stage grid min-h-screen place-items-center px-5 py-10 text-text-primary"><section className="auth-card ui-card w-full max-w-md p-7 sm:p-10"><p className="auth-kicker">Private client invitation</p><h1 className="mt-3 text-3xl font-bold">Join {businessDisplayName}</h1><p className="mt-3 text-sm leading-6 text-text-muted">This one-time invitation is bound to {email}. Create an account with that email only; Capture Tracker will create your sole-owner workspace after you sign in and accept.</p><form className="mt-7 grid gap-4" onSubmit={submit}><label className="grid gap-1 text-sm font-bold">Name<input required autoComplete="name" className="ui-input" name="name" /></label><label className="grid gap-1 text-sm font-bold">Email<input required readOnly autoComplete="email" className="ui-input" name="email" type="email" value={email} /></label><label className="grid gap-1 text-sm font-bold">Password<input required autoComplete="new-password" className="ui-input" minLength={12} name="password" type="password" /></label><label className="grid gap-1 text-sm font-bold">Confirm password<input required autoComplete="new-password" className="ui-input" minLength={12} name="confirmPassword" type="password" /></label><button className="ui-button ui-button-primary min-h-11" disabled={submitting}>{submitting ? "Creating account…" : "Create account"}</button>{message && <p role="status" className="text-sm">{message}</p>}</form><Link className="mt-5 inline-block text-sm font-bold text-brand-teal underline" href={`/sign-in?invite=${encodeURIComponent(token)}`}>Already have an account? Sign in</Link></section></main>;
}
