"use client";

import { useActionState, useState } from "react";
import { Card, PageHeader, StatusBadge } from "./ui";
import type { InvoiceActionState } from "@/app/app/money/invoices/actions";

const initial: InvoiceActionState = { status: "idle", message: null };
type Action = (state: InvoiceActionState, form: FormData) => Promise<InvoiceActionState>;

export function InvoiceCenter({ customers, accounts, invoices, customerAction, invoiceAction, issueAction, paymentAction }: { customers: Array<{ id: string; businessName: string }>; accounts: Array<{ id: string; name: string }>; invoices: Array<{ id: string; invoiceNumber: string; customer: string; total: string; paid: string; status: string; dueDate: string | null }>; customerAction: Action; invoiceAction: Action; issueAction: Action; paymentAction: Action }) {
  const [customer, saveCustomer, customerPending] = useActionState(customerAction, initial); const [invoice, saveInvoice, invoicePending] = useActionState(invoiceAction, initial); const [issue, submitIssue] = useActionState(issueAction, initial); const [payment, submitPayment] = useActionState(paymentAction, initial); const [show, setShow] = useState(false);
  return <><PageHeader eyebrow="Money" title="Invoices" description="Create, issue, and record owner-confirmed customer payments. Payment processing is not included." action={<button className="ui-button ui-button-primary min-h-11 px-4" onClick={() => setShow(!show)}>{show ? "Hide forms" : "New invoice"}</button>} />
    {show && <div className="mt-6 grid gap-6 lg:grid-cols-2"><form action={saveCustomer} className="ui-card grid gap-3 p-5"><h2 className="font-bold">New customer</h2><label className="text-sm font-bold text-text-muted">Business/customer name<input required className="ui-input mt-1" name="businessName" /></label><label className="text-sm font-bold text-text-muted">Contact name<input className="ui-input mt-1" name="contactName" /></label><label className="text-sm font-bold text-text-muted">Email<input className="ui-input mt-1" name="email" type="email" /></label>{customer.message && <p className="text-sm font-bold">{customer.message}</p>}<button disabled={customerPending} className="ui-button ui-button-secondary min-h-11 px-4">Save customer</button></form><form action={saveInvoice} className="ui-card grid gap-3 p-5"><h2 className="font-bold">New invoice</h2><label className="text-sm font-bold text-text-muted">Customer<select required className="ui-input mt-1" name="customerId" defaultValue=""><option value="" disabled>Select customer</option>{customers.map((item) => <option value={item.id} key={item.id}>{item.businessName}</option>)}</select></label><label className="text-sm font-bold text-text-muted">Service description<input required className="ui-input mt-1" name="description" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold text-text-muted">Quantity<input required className="ui-input mt-1" name="quantity" defaultValue="1" inputMode="decimal" /></label><label className="text-sm font-bold text-text-muted">Rate<input required className="ui-input mt-1" name="rate" inputMode="decimal" /></label><label className="text-sm font-bold text-text-muted">Issue date<input required className="ui-input mt-1" name="issueDate" type="date" /></label><label className="text-sm font-bold text-text-muted">Due date<input required className="ui-input mt-1" name="dueDate" type="date" /></label></div><label className="text-sm font-bold text-text-muted">Payment instructions<textarea className="ui-input mt-1" name="paymentInstructions" /></label>{invoice.message && <p className="text-sm font-bold">{invoice.message}</p>}<button disabled={invoicePending} className="ui-button ui-button-primary min-h-11 px-4">Create draft</button></form></div>}
    <Card className="mt-6 p-5"><h2 className="font-bold">Invoice register</h2>{invoices.length ? <div className="mt-3 space-y-3">{invoices.map((item) => <section key={item.id} className="border-t border-border-subtle pt-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{item.invoiceNumber} · {item.customer}</p><p className="money-value text-sm">${item.total} · ${item.paid} received{item.dueDate ? ` · Due ${item.dueDate}` : ""}</p></div><div className="flex items-center gap-3"><StatusBadge tone={item.status === "PAID" ? "success" : "warning"}>{item.status.replaceAll("_", " ")}</StatusBadge>{item.status === "DRAFT" && <form action={submitIssue}><input type="hidden" name="invoiceId" value={item.id}/><button className="ui-button ui-button-secondary min-h-10 px-3">Issue</button></form>}</div></div>{["ISSUED", "OVERDUE", "PARTIALLY_PAID"].includes(item.status) && <details className="mt-3"><summary className="cursor-pointer text-sm font-bold text-brand-navy">Record payment</summary><form action={submitPayment} className="mt-3 grid gap-3 sm:grid-cols-4"><input type="hidden" name="invoiceId" value={item.id}/><label className="text-sm font-bold text-text-muted">Amount<input required className="ui-input mt-1" name="amount" inputMode="decimal"/></label><label className="text-sm font-bold text-text-muted">Received<input required className="ui-input mt-1" name="receivedAt" type="date"/></label><label className="text-sm font-bold text-text-muted">Deposit account<select className="ui-input mt-1" name="financialAccountId" defaultValue=""><option value="">Choose account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="text-sm font-bold text-text-muted">Reference<input className="ui-input mt-1" name="reference" maxLength={500}/></label><button className="ui-button ui-button-primary min-h-11 px-3 sm:col-span-4">Record owner-confirmed payment</button></form></details>}</section>)}</div> : <p className="mt-3 text-sm text-text-muted">No invoices recorded.</p>}{issue.message && <p className="mt-4 text-sm font-bold">{issue.message}</p>}{payment.message && <p className="mt-4 text-sm font-bold">{payment.message}</p>}</Card></>;
}
