"use client";
import { useActionState, useState } from "react";
import { Card, PageHeader, StatusBadge } from "./ui";
import type { MileageActionState } from "@/app/app/taxes/mileage/actions";
type Action = (state: MileageActionState, form: FormData) => Promise<MileageActionState>; const initial: MileageActionState = { status: "idle", message: null };
export function MileageCenter({ policies, trips, policyAction, tripAction, reimbursementAction }: { policies: Array<{ id: string; effectiveDate: string; endDate: string | null; rate: string; source: string }>; trips: Array<{ id: string; date: string; origin: string; destination: string; purpose: string | null; miles: string; amount: string | null; claimed: boolean }>; policyAction: Action; tripAction: Action; reimbursementAction: Action }) {
  const [policy, submitPolicy] = useActionState(policyAction, initial); const [trip, submitTrip] = useActionState(tripAction, initial); const [reimbursement, submitReimbursement] = useActionState(reimbursementAction, initial); const [showPolicy, setShowPolicy] = useState(false);
  return <><PageHeader eyebrow="Owner money" title="Mileage" description="Substantiate business trips, apply an owner-approved rate, then create an accountable-plan reimbursement workpaper." action={<button className="ui-button ui-button-secondary min-h-11 px-4" onClick={() => setShowPolicy(!showPolicy)}>{showPolicy ? "Hide policy" : "Mileage policy"}</button>}/>
    {showPolicy && <Card className="mt-6 p-5"><h2 className="font-bold">Mileage policy</h2><p className="mt-1 text-sm text-text-muted">Enter the owner-approved rate and an authoritative source. Capture Tracker does not determine tax eligibility.</p><form action={submitPolicy} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold text-text-muted">Effective date<input required className="ui-input mt-1" name="effectiveDate" type="date"/></label><label className="text-sm font-bold text-text-muted">End date (optional)<input className="ui-input mt-1" name="effectiveEndDate" type="date"/></label><label className="text-sm font-bold text-text-muted">Rate per mile<input required className="ui-input mt-1" name="ratePerMile" inputMode="decimal" placeholder="0.0000"/></label><label className="text-sm font-bold text-text-muted">Authoritative source<input required className="ui-input mt-1" name="sourceReference" placeholder="IRS notice or approved policy reference"/></label><button className="ui-button ui-button-primary min-h-11 px-4">Save policy</button>{policy.message && <p role={policy.status === "error" ? "alert" : "status"} className="self-center text-sm font-bold">{policy.message}</p>}</form><div className="mt-5 space-y-2 border-t border-border-subtle pt-4"><h3 className="text-sm font-bold">Rate history</h3>{policies.length ? policies.map((item) => <p className="text-sm text-text-muted" key={item.id}>{item.effectiveDate}{item.endDate ? ` to ${item.endDate}` : " onward"} · ${item.rate}/mile · {item.source}</p>) : <p className="text-sm text-text-muted">MILEAGE POLICY NEEDS REVIEW — no dated rate is available yet.</p>}</div></Card>}
    <Card className="mt-6 p-5"><h2 className="font-bold">Log a business trip</h2><form action={submitTrip} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold text-text-muted">Trip date<input required className="ui-input mt-1" name="tripDate" type="date"/></label><label className="text-sm font-bold text-text-muted">Miles<input required className="ui-input mt-1" name="miles" inputMode="decimal" placeholder="0.00"/></label><label className="text-sm font-bold text-text-muted">Start<input required className="ui-input mt-1" name="originDescription"/></label><label className="text-sm font-bold text-text-muted">Destination<input required className="ui-input mt-1" name="destinationDescription"/></label><label className="text-sm font-bold text-text-muted sm:col-span-2">Business purpose<textarea required className="ui-input mt-1 min-h-20" name="businessPurpose"/></label><label className="text-sm font-bold text-text-muted">Vehicle/reference<input className="ui-input mt-1" name="vehicleReference"/></label><label className="text-sm font-bold text-text-muted">Notes<input className="ui-input mt-1" name="notes"/></label><button className="ui-button ui-button-primary min-h-11 px-4">Save trip</button>{trip.message && <p role={trip.status === "error" ? "alert" : "status"} className="self-center text-sm font-bold">{trip.message}</p>}</form></Card>
    <Card className="mt-6 p-5"><h2 className="font-bold">Mileage log</h2>{trips.length ? <div className="mt-3 space-y-3">{trips.map((item) => <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border-subtle pt-3" key={item.id}><div><p className="font-bold">{item.origin} → {item.destination}</p><p className="text-sm text-text-muted">{item.date} · {item.miles} miles · {item.purpose ?? "Business purpose missing"}</p></div><div className="flex items-center gap-3">{item.amount ? <span className="money-value font-bold">${item.amount}</span> : <StatusBadge tone="warning">POLICY NEEDS REVIEW</StatusBadge>}{item.amount && !item.claimed && <form action={submitReimbursement}><input type="hidden" name="tripId" value={item.id}/><button className="ui-button ui-button-secondary min-h-10 px-3">Create reimbursement</button></form>}</div></div>)}</div> : <p className="mt-3 text-sm text-text-muted">No mileage trips recorded.</p>}{reimbursement.message && <p role={reimbursement.status === "error" ? "alert" : "status"} className="mt-4 text-sm font-bold">{reimbursement.message}</p>}</Card></>;
}
