"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import type { MileageActionState } from "@/app/app/taxes/mileage/actions";
import { Card, EmptyState, PageHeader, StatusBadge } from "./ui";

type Action = (state: MileageActionState, form: FormData) => Promise<MileageActionState>; const initial: MileageActionState = { status: "idle", message: null };
type Props = { policies: Array<{ id: string; effectiveDate: string; endDate: string | null; rate: string; source: string }>; trips: Array<{ id: string; date: string; origin: string; destination: string; purpose: string | null; miles: string; amount: string | null; claimed: boolean }>; policyAction: Action; tripAction: Action; reimbursementAction: Action; canMutate?: boolean };

export function MileageCenter({ policies, trips, policyAction, tripAction, reimbursementAction, canMutate = true }: Props) {
  const [policy, submitPolicy] = useActionState(policyAction, initial); const [trip, submitTrip] = useActionState(tripAction, initial); const [reimbursement, submitReimbursement] = useActionState(reimbursementAction, initial); const [showPolicy, setShowPolicy] = useState(false);
  return <>
    <PageHeader eyebrow="Me & my S-Corp" title="Mileage" description="Record business driving with its purpose, preserve a dated owner-approved rate, and create an S-Corp reimbursement workpaper." action={canMutate ? <button className="ui-button ui-button-secondary min-h-11 px-4" onClick={() => setShowPolicy(!showPolicy)}>{showPolicy ? "Hide policy" : "Mileage policy"}</button> : <StatusBadge tone="locked">Read-only professional review</StatusBadge>}/>
    {showPolicy && canMutate ? <Card className="mt-6 p-5"><h2 className="font-bold">Mileage policy</h2><p className="mt-1 text-sm text-text-muted">Enter the owner-approved rate and an authoritative source. Capture Tracker does not determine tax eligibility.</p><form action={submitPolicy} className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Effective date"><input required className="ui-input mt-1" name="effectiveDate" type="date"/></Field><Field label="End date (optional)"><input className="ui-input mt-1" name="effectiveEndDate" type="date"/></Field><Field label="Rate per mile"><input required className="ui-input mt-1" name="ratePerMile" inputMode="decimal" placeholder="0.0000"/></Field><Field label="Authoritative source"><input required className="ui-input mt-1" name="sourceReference" placeholder="IRS notice or approved policy reference"/></Field><button className="ui-button ui-button-primary min-h-11 px-4">Save policy</button>{policy.message ? <p role={policy.status === "error" ? "alert" : "status"} className="self-center text-sm font-bold">{policy.message}</p> : null}</form><div className="mt-5 space-y-2 border-t border-border-subtle pt-4"><h3 className="text-sm font-bold">Rate history</h3>{policies.length ? policies.map((item) => <p className="text-sm text-text-muted" key={item.id}>{item.effectiveDate}{item.endDate ? ` to ${item.endDate}` : " onward"} · ${item.rate}/mile · {item.source}</p>) : <p className="text-sm text-text-muted">MILEAGE POLICY NEEDS REVIEW — no dated rate is available yet.</p>}</div></Card> : null}
    {canMutate ? <Card className="mt-6 p-5" ><div id="record-trip"><h2 className="font-bold">Record a business trip</h2><p className="mt-1 text-sm text-text-muted">Keep the trip, exact miles, and business purpose together so reimbursement evidence is complete.</p></div><form action={submitTrip} className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Trip date"><input required className="ui-input mt-1" name="tripDate" type="date"/></Field><Field label="Miles"><input required className="ui-input mt-1" name="miles" inputMode="decimal" placeholder="0.00"/></Field><Field label="Start"><input required className="ui-input mt-1" name="originDescription"/></Field><Field label="Destination"><input required className="ui-input mt-1" name="destinationDescription"/></Field><label className="text-sm font-bold text-text-muted sm:col-span-2">Business purpose<textarea required className="ui-input mt-1 min-h-20" name="businessPurpose"/></label><Field label="Vehicle/reference"><input className="ui-input mt-1" name="vehicleReference"/></Field><Field label="Notes"><input className="ui-input mt-1" name="notes"/></Field><button className="ui-button ui-button-primary min-h-11 px-4">Save trip</button>{trip.message ? <p role={trip.status === "error" ? "alert" : "status"} className="self-center text-sm font-bold">{trip.message}</p> : null}</form></Card> : null}
    <Card className="mt-6 p-5"><h2 className="font-bold">Mileage log</h2>{trips.length ? <div className="mt-3 space-y-3">{trips.map((item) => <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border-subtle pt-3" key={item.id}><div><p className="font-bold">{item.origin} → {item.destination}</p><p className="text-sm text-text-muted">{item.date} · {item.miles} miles · {item.purpose ?? "Business purpose missing"}</p></div><div className="flex items-center gap-3">{item.amount ? <span className="money-value font-bold">${item.amount}</span> : <StatusBadge tone="warning">POLICY NEEDS REVIEW</StatusBadge>}{canMutate && item.amount && !item.claimed ? <form action={submitReimbursement}><input type="hidden" name="tripId" value={item.id}/><button className="ui-button ui-button-secondary min-h-10 px-3">Create reimbursement</button></form> : null}</div></div>)}</div> : <EmptyState title="No business mileage yet"><span>Record business driving with its purpose and exact miles. Capture Tracker uses the substantiated trip to prepare the S-Corp reimbursement workpaper.</span>{canMutate ? <a className="ui-button ui-button-primary mt-4 inline-flex min-h-11 items-center px-4" href="#record-trip">Record mileage</a> : null}</EmptyState>}{reimbursement.message ? <p role={reimbursement.status === "error" ? "alert" : "status"} className="mt-4 text-sm font-bold">{reimbursement.message}</p> : null}<div className="mt-5 flex flex-wrap gap-4 border-t border-border-subtle pt-4 text-sm"><Link className="ui-link font-bold" href="/app/taxes/owner-money">Open reimbursement work →</Link><Link className="ui-link font-bold" href="/app/reports/operations?report=mileage-reimbursements">Mileage reimbursement summary →</Link></div></Card>
  </>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-bold text-text-muted">{label}{children}</label>; }
