import Link from "next/link";
import type { getOperationalReport, OperationalReportKind } from "@/lib/data/operational-reports";
import { ButtonLink, EmptyState } from "./ui";

type Data = Awaited<ReturnType<typeof getOperationalReport>>;
const labels: Array<[OperationalReportKind, string]> = [["invoice-register", "Invoice register"], ["open-invoices", "Open invoices"], ["ar-aging", "AR aging"], ["invoice-payments", "Invoice payments"], ["bill-register", "Bill register"], ["open-bills", "Open bills"], ["ap-aging", "AP aging"], ["bill-payments", "Bill payments"], ["mileage-log", "Mileage log"], ["mileage-reimbursements", "Mileage reimbursements"]];
const reportCopy: Record<OperationalReportKind, string> = {
  "invoice-register": "Every customer invoice and its current payment status.", "open-invoices": "Customers who still owe the business money.", "ar-aging": "Who still owes the business money, grouped by how long the invoice has been outstanding.", "invoice-payments": "Recorded incoming payments and their supporting bank evidence.", "bill-register": "Every vendor bill and its current payment status.", "open-bills": "Vendor obligations the business still needs to pay.", "ap-aging": "What the business owes, grouped by how long the bill has been outstanding.", "bill-payments": "Recorded outgoing payments and their supporting bank evidence.", "mileage-log": "Substantiated business trips and reimbursement status.", "mileage-reimbursements": "Mileage amounts included in or still waiting for reimbursement work.",
};

export function OperationalReports({ data }: { data: Data }) {
  const aging = data.report === "ar-aging" ? data.arAging : data.report === "ap-aging" ? data.apAging : null;
  return <section className="space-y-6"><header className="ui-page-header"><p className="ui-page-eyebrow font-bold uppercase">Reports by business question</p><h1 className="ui-page-title mt-2 text-3xl font-bold tracking-[-0.055em]">{labels.find(([kind]) => kind === data.report)?.[1]}</h1><p className="ui-page-description mt-3 text-sm text-text-muted">{reportCopy[data.report]} Bank evidence supports payments; it never replaces owner review.</p></header><nav className="report-tabs flex gap-2 overflow-x-auto" aria-label="Operational report views">{labels.map(([kind, label]) => <Link key={kind} href={`/app/reports/operations?report=${kind}`} className={`min-h-10 shrink-0 rounded px-3 py-2 text-sm font-bold ${data.report === kind ? "bg-brand-navy text-white" : "bg-surface-secondary text-text-muted"}`}>{label}</Link>)}</nav>{aging ? <AgingReport data={data} aging={aging} /> : data.report === "mileage-log" || data.report === "mileage-reimbursements" ? <MileageTable rows={data.mileage}/> : data.report === "invoice-payments" || data.report === "bill-payments" ? <PaymentTable rows={data.payments} kind={data.report}/> : <RegisterTable rows={data.invoices} kind={data.report}/>}<Pagination report={data.report} page={data.page} hasNext={data.hasNextPage}/><p><Link className="ui-link text-sm font-bold" href="/app/reports">← Back to reports by question</Link></p></section>;
}

function AgingReport({ data, aging }: { data: Data; aging: NonNullable<Data["arAging"]> }) {
  const empty = aging.every((item) => Number(item.amount) === 0);
  return <section className="ui-card p-5"><h2 className="font-bold">{data.report === "ar-aging" ? "Who owes me money?" : "What do I owe?"}</h2>{empty ? <EmptyState title={data.report === "ar-aging" ? "No receivables yet" : "No payables yet"}><span>{data.report === "ar-aging" ? "Receivables appear here after an invoice is issued and remain until payment is recorded." : "Payables appear here after a bill is recorded and remain until payment is recorded."}</span><ButtonLink className="mt-4" href={data.report === "ar-aging" ? "/app/money/invoices?new=invoice" : "/app/money/bills?new=bill"}>{data.report === "ar-aging" ? "Create invoice" : "Add bill"}</ButtonLink></EmptyState> : <div className="mt-4 grid gap-3 sm:grid-cols-5">{aging.map((item) => <div key={item.bucket}><p className="text-xs font-bold text-text-muted">{item.bucket.replace("_", "–")}</p><p className="money-value mt-1 font-bold">${item.amount}</p></div>)}</div>}</section>;
}

function RegisterTable({ rows, kind }: { rows: Data["invoices"]; kind: OperationalReportKind }) {
  if (!rows.length) return <EmptyState title={kind.includes("invoice") ? "No invoices to report" : "No bills to report"}><span>{kind.includes("invoice") ? "Create and issue a service invoice to begin tracking what customers owe." : "Record a vendor bill to begin tracking what the business owes."}</span><ButtonLink className="mt-4" href={kind.includes("invoice") ? "/app/money/invoices?new=invoice" : "/app/money/bills?new=bill"}>{kind.includes("invoice") ? "Create invoice" : "Add bill"}</ButtonLink></EmptyState>;
  return <section className="ui-card overflow-hidden"><div className="divide-y divide-border-subtle min-[720px]:hidden">{rows.map((row) => <article className="p-4" key={row.id}><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{row.party}</h2><p className="mt-1 text-xs text-text-muted">{row.reference} · Due {row.dueDate ?? "not set"}</p></div><span className="text-xs font-bold">{row.status.replaceAll("_", " ")}</span></div><div className="mt-3 flex justify-between gap-3 text-sm"><span>Total <b className="money-value">${row.total}</b></span><span>Outstanding <b className="money-value">${row.outstanding}</b></span></div></article>)}</div><div className="hidden overflow-x-auto min-[720px]:block"><table className="w-full min-w-[46rem] text-sm"><thead className="border-b border-border-subtle text-left text-text-muted"><tr><th className="p-3">Party</th><th className="p-3">Reference</th><th className="p-3">Due</th><th className="p-3 text-right">Total</th><th className="p-3 text-right">Outstanding</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-border-subtle"><td className="p-3 font-bold">{row.party}</td><td className="p-3">{row.reference}</td><td className="p-3">{row.dueDate ?? "—"}</td><td className="money-value p-3 text-right">${row.total}</td><td className="money-value p-3 text-right">${row.outstanding}</td><td className="p-3">{row.status.replaceAll("_", " ")}</td></tr>)}</tbody></table></div></section>;
}

function PaymentTable({ rows, kind }: { rows: Data["payments"]; kind: OperationalReportKind }) {
  if (!rows.length) return <EmptyState title="No payments recorded yet">{kind === "invoice-payments" ? "Customer payments appear after an owner records or matches incoming payment evidence." : "Vendor payments appear after an owner records or matches outgoing payment evidence."}</EmptyState>;
  return <section className="ui-card overflow-hidden"><div className="divide-y divide-border-subtle min-[720px]:hidden">{rows.map((row) => <article className="p-4" key={row.id}><div className="flex justify-between gap-3"><div><h2 className="font-bold">{row.party}</h2><p className="mt-1 text-xs text-text-muted">{row.date} · {row.reference}</p></div><b className="money-value">${row.amount}</b></div><p className="mt-3 text-xs font-bold text-text-muted">Bank evidence: {row.bankEvidence ? "Attached" : "Not yet attached"}</p></article>)}</div><div className="hidden overflow-x-auto min-[720px]:block"><table className="w-full min-w-[42rem] text-sm"><thead className="border-b border-border-subtle text-left text-text-muted"><tr><th className="p-3">Date</th><th className="p-3">Party</th><th className="p-3">Reference</th><th className="p-3 text-right">Amount</th><th className="p-3">Bank evidence</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-border-subtle"><td className="p-3">{row.date}</td><td className="p-3 font-bold">{row.party}</td><td className="p-3">{row.reference}</td><td className="money-value p-3 text-right">${row.amount}</td><td className="p-3">{row.bankEvidence ? "Attached" : "Not yet attached"}</td></tr>)}</tbody></table></div></section>;
}

function MileageTable({ rows }: { rows: Data["mileage"] }) {
  if (!rows.length) return <EmptyState title="No business mileage yet"><span>Record business driving with an exact distance and purpose to create the S-Corp reimbursement workpaper.</span><ButtonLink className="mt-4" href="/app/taxes/mileage#record-trip">Record mileage</ButtonLink></EmptyState>;
  return <section className="ui-card overflow-hidden"><div className="divide-y divide-border-subtle min-[720px]:hidden">{rows.map((row) => <article className="p-4" key={row.id}><h2 className="font-bold">{row.description}</h2><p className="mt-1 text-xs text-text-muted">{row.date} · {row.purpose ?? "Business purpose needs review"}</p><div className="mt-3 flex justify-between gap-3 text-sm"><b className="money-value">{row.miles} miles</b><span>{row.reimbursement ? `$${row.reimbursement}` : "Policy needed"} · {row.claimed ? "Claim created" : "Unreimbursed"}</span></div></article>)}</div><div className="hidden overflow-x-auto min-[720px]:block"><table className="w-full min-w-[46rem] text-sm"><thead className="border-b border-border-subtle text-left text-text-muted"><tr><th className="p-3">Date</th><th className="p-3">Trip</th><th className="p-3">Business purpose</th><th className="p-3 text-right">Miles</th><th className="p-3 text-right">Reimbursement</th><th className="p-3">State</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-border-subtle"><td className="p-3">{row.date}</td><td className="p-3 font-bold">{row.description}</td><td className="p-3">{row.purpose ?? "MILEAGE SUBSTANTIATION NEEDS REVIEW"}</td><td className="money-value p-3 text-right">{row.miles}</td><td className="money-value p-3 text-right">{row.reimbursement ? `$${row.reimbursement}` : "Policy needed"}</td><td className="p-3">{row.claimed ? "Claim created" : "Unreimbursed"}</td></tr>)}</tbody></table></div></section>;
}

function Pagination({ report, page, hasNext }: { report: string; page: number; hasNext: boolean }) { return <div className="flex justify-between text-sm">{page > 1 ? <Link className="ui-link" href={`/app/reports/operations?report=${report}&page=${page - 1}`}>Previous page</Link> : <span/>}{hasNext ? <Link className="ui-link" href={`/app/reports/operations?report=${report}&page=${page + 1}`}>Next page</Link> : null}</div>; }
