"use client";

import { useActionState } from "react";

type Invitation = { id: string; invitedEmail: string; businessDisplayName: string; status: string; createdAt: Date; expiresAt: Date; acceptedAt: Date | null; revokedAt: Date | null };
type State = { ok: boolean; message?: string; invitationUrl?: string };
type Action = (state: State, form: FormData) => Promise<State>;

export function OperatorOnboardingPanel({ invitations, createAction, revokeAction, expireAction }: { invitations: Invitation[]; createAction: Action; revokeAction: Action; expireAction: Action }) {
  const [created, create] = useActionState(createAction, { ok: false });
  return <main className="auth-stage min-h-screen px-5 py-10 text-text-primary"><section className="mx-auto grid w-full max-w-5xl gap-6"><header className="ui-card p-6"><p className="auth-kicker">Platform operator</p><h1 className="mt-2 text-3xl font-bold">Client onboarding invitations</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-text-muted">Create one-time, email-bound invitations only. This surface never grants access to client books, reports, documents, or tenant memberships.</p></header>
    <section className="ui-card p-6"><h2 className="text-xl font-bold">Create invitation</h2><form action={create} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Client owner email<input required className="ui-input mt-1" name="invitedEmail" type="email" /></label><label className="text-sm font-bold">Owner display name<input required className="ui-input mt-1" name="ownerDisplayName" maxLength={120} /></label><label className="text-sm font-bold">Legal business name<input required className="ui-input mt-1" name="businessLegalName" maxLength={160} /></label><label className="text-sm font-bold">Workspace display name<input required className="ui-input mt-1" name="businessDisplayName" maxLength={160} /></label><div className="sm:col-span-2"><button className="ui-button ui-button-primary min-h-11 px-4">Create one-time invitation</button></div></form>{created.message && <p role="status" className="mt-3 text-sm">{created.message}</p>}{created.invitationUrl && <div className="mt-4 rounded border border-border-subtle p-4"><p className="text-sm font-bold">Copy invitation link</p><input aria-label="Invitation link" className="ui-input mt-2 w-full" readOnly value={created.invitationUrl} onFocus={(event) => event.currentTarget.select()} /><p className="mt-2 text-xs text-text-muted">Send it manually to the intended client. It expires in 72 hours and is shown only now.</p></div>}</section>
    <section className="ui-card overflow-hidden"><header className="border-b border-border-subtle p-6"><h2 className="text-xl font-bold">Invitation status</h2></header>{invitations.length ? <ul className="divide-y divide-border-subtle">{invitations.map((invitation) => <li key={invitation.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_auto]"><div><p className="font-bold">{invitation.businessDisplayName}</p><p className="mt-1 text-sm text-text-muted">{invitation.invitedEmail} · {invitation.status}</p><p className="mt-1 text-xs text-text-muted">Expires {invitation.expiresAt.toLocaleString()}{invitation.acceptedAt ? ` · Accepted ${invitation.acceptedAt.toLocaleString()}` : ""}</p></div>{invitation.status === "PENDING" ? <div className="flex flex-wrap gap-2"><form action={async (form) => { await revokeAction({ ok: false }, form); }}><input type="hidden" name="invitationId" value={invitation.id}/><button className="ui-button ui-button-secondary min-h-10 px-3 text-sm">Revoke</button></form><form action={async (form) => { await expireAction({ ok: false }, form); }}><input type="hidden" name="invitationId" value={invitation.id}/><button className="ui-button ui-button-secondary min-h-10 px-3 text-sm">Expire now</button></form></div> : null}</li>)}</ul> : <p className="p-6 text-sm text-text-muted">No invitations created by this operator.</p>}</section>
  </section></main>;
}
