"use client";

import { useActionState, useState } from "react";
import { Card, InlineAlert, PageHeader, StatusBadge } from "./ui";

export type OwnerMoneyActionState = { status: "idle" | "success" | "error"; message: string | null };
const initialState: OwnerMoneyActionState = { status: "idle", message: null };
type Data = { year: number; totals: { salary: string; distributions: string; reimbursementsDue: string; contributions: string; longTermLiabilities: string }; claims: Array<{ id: string; status: string; totalAmount: string; createdAt: string; paid: boolean; expense: { purpose: string; merchant: string | null; hasDocument: boolean; incurredAt: string } | null }>; distributions: Array<{ id: string; amount: string; status: string; date: string; memo: string | null }>; documents: Array<{ id: string; originalFilename: string }> };

export function OwnerMoneyExperience({ data, action }: { data: Data; action: (state: OwnerMoneyActionState, formData: FormData) => Promise<OwnerMoneyActionState> }) {
  const [state, submit, pending] = useActionState(action, initialState);
  const [showForm, setShowForm] = useState(false);
  const [idempotencyKey] = useState(() => crypto.randomUUID());
  return <>
    <PageHeader eyebrow="Owner money" title="Owner money center" description="Keep salary, distributions, reimbursements, contributions, and shareholder loans separate. Totals are derived from recorded books; this workspace does not execute payments." action={<button className="ui-button ui-button-primary min-h-11 rounded-[var(--radius-sm)] bg-brand-navy px-4 text-sm font-bold text-white" onClick={() => setShowForm(!showForm)}>{showForm ? "Hide reimbursement form" : "Record personally paid expense"}</button>} />
    <InlineAlert title="Classify transfers deliberately" tone="warning">Company-to-owner and owner-to-company transfers are not automatically guessed. Review payroll, distributions, reimbursements, contributions, and loans as distinct accounting treatments.</InlineAlert>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label={`Net salary ${data.year}`} value={data.totals.salary} /><Metric label="Distributions" value={data.totals.distributions} /><Metric label="Reimbursements due" value={data.totals.reimbursementsDue} /><Metric label="Owner contributions" value={data.totals.contributions} /><Metric label="Long-term liabilities" value={data.totals.longTermLiabilities} /></section>
    <p className="mt-3 text-sm text-text-muted">Long-term liabilities are shown separately until the business explicitly identifies a liability as a shareholder loan. This workspace does not infer loan treatment from a transfer description.</p>
    {showForm && <form action={submit} className="ui-card mt-6 max-w-3xl p-5"><input type="hidden" name="idempotencyKey" value={idempotencyKey} /><h2 className="text-lg font-bold">Personally paid business expense</h2><p className="mt-1 text-sm text-text-muted">Creates a documented reimbursement claim only. It does not pay, approve, or post an expense journal.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Incurred date"><input required className="ui-input mt-1" name="incurredAt" type="date" /></Field><Field label="Exact amount"><input required className="ui-input mt-1" name="amount" inputMode="decimal" placeholder="0.00" /></Field><Field label="Expense type"><select className="ui-input mt-1" name="expenseType" defaultValue="SUPPLIES"><option value="SUPPLIES">Supplies</option><option value="MILEAGE">Mileage</option><option value="AIRFARE">Airfare</option><option value="LODGING">Lodging</option><option value="MEALS">Meals</option><option value="PARKING">Parking</option><option value="TOLLS">Tolls</option><option value="PHONE">Phone</option><option value="INTERNET">Internet</option><option value="EDUCATION">Education</option><option value="OTHER">Other</option></select></Field><Field label="Merchant (optional)"><input className="ui-input mt-1" name="merchantName" maxLength={160} /></Field></div><Field label="Business purpose"><textarea required className="ui-input mt-1 min-h-20" name="businessPurpose" maxLength={500} /></Field><Field label="Supporting receipt (optional)"><select className="ui-input mt-1" name="documentId" defaultValue=""><option value="">No receipt linked yet</option>{data.documents.map((document) => <option key={document.id} value={document.id}>{document.originalFilename}</option>)}</select></Field><Field label="Notes (optional)"><textarea className="ui-input mt-1 min-h-16" name="notes" maxLength={1000} /></Field>{state.message && <p role={state.status === "error" ? "alert" : "status"} className="mt-4 text-sm font-bold">{state.message}</p>}<button disabled={pending} className="mt-4 min-h-11 rounded-[var(--radius-sm)] bg-brand-navy px-4 text-sm font-bold text-white disabled:opacity-60">{pending ? "Recording…" : "Create reimbursement claim"}</button></form>}
    <Card className="mt-6 p-5"><h2 className="font-bold">Reimbursement lifecycle</h2><p className="mt-1 text-sm text-text-muted">Personally paid → documented → reviewed → reimbursement due → payment detected → matched → reimbursed. Payment matching and approval remain controlled accounting steps.</p>{data.claims.length ? <div className="mt-4 space-y-3">{data.claims.map((claim) => <div className="border-t border-border-subtle pt-3 text-sm" key={claim.id}><div className="flex flex-wrap justify-between gap-2"><span className="font-bold">${claim.totalAmount} · {claim.expense?.merchant ?? "Personally paid expense"}</span><StatusBadge tone={claim.paid ? "success" : "warning"}>{claim.paid ? "Payment matched" : claim.status.replaceAll("_", " ")}</StatusBadge></div><p className="mt-1 text-text-muted">{claim.expense?.purpose ?? "Expense detail unavailable"} · {claim.expense?.hasDocument ? "Receipt linked" : "Receipt needed"}</p></div>)}</div> : <p className="mt-3 text-sm text-text-muted">No reimbursement claims recorded.</p>}</Card>
    <Card className="mt-6 p-5"><h2 className="font-bold">Recorded distributions</h2>{data.distributions.length ? <div className="mt-3 space-y-2">{data.distributions.map((item) => <p className="border-t border-border-subtle pt-2 text-sm" key={item.id}>${item.amount} · {new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(item.date))} · {item.status.replaceAll("_", " ")}{item.memo ? ` · ${item.memo}` : ""}</p>)}</div> : <p className="mt-3 text-sm text-text-muted">No distributions recorded this year.</p>}</Card>
  </>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-4 block text-sm font-bold text-text-muted">{label}{children}</label>; }
function Metric({ label, value }: { label: string; value: string }) { return <Card className="metric-card p-4"><p className="text-xs font-bold text-text-muted">{label}</p><p className="money-value mt-2 text-xl font-bold text-brand-navy">${value}</p></Card>; }
