"use client";
import { useActionState, useMemo, useState } from "react";
import { InlineAlert, StatusBadge } from "./ui";
import type { AccountingActionState } from "@/lib/services/reconciliation-action";
type Detail = { id: string; accountName: string; statementStartDate: string; statementEndDate: string; statementOpeningBalance: string; statementEndingBalance: string; calculatedBalance: string; difference: string; status: string; version: number; completedAt: string | null; selectedIds: string[]; candidates: Array<{ id: string; postedAt: string; description: string; amount: string; direction: string; status: string }> };
type Action = (state: AccountingActionState, form: FormData) => Promise<AccountingActionState>;
export function ReconciliationExperience({ detail, saveAction, finalizeAction }: { detail: Detail; saveAction: Action; finalizeAction: Action }) { const [selected, setSelected] = useState(detail.selectedIds); const [saveState, save] = useActionState(saveAction, { status: "idle", message: null }); const [finalizeState, finalize] = useActionState(finalizeAction, { status: "idle", message: null }); const editable = detail.status !== "COMPLETED"; const selectedRows = useMemo(() => new Set(selected), [selected]); return <>
  <section className="ui-card grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Statement ending" value={`$${detail.statementEndingBalance}`} /><Info label="Cleared book balance" value={`$${detail.calculatedBalance}`} /><Info label="Difference (statement − book)" value={`$${detail.difference}`} /><div><p className="text-xs font-bold uppercase tracking-wide text-text-muted">Status</p><StatusBadge tone={editable ? "warning" : "success"}>{detail.status}</StatusBadge></div></section>
  {!editable && <div className="mt-5"><InlineAlert title="Immutable reconciliation" tone="locked">This completed reconciliation is preserved as accounting evidence. It cannot be reopened or edited.</InlineAlert></div>}
  {editable && <form action={save} className="ui-card mt-5 overflow-hidden"><input type="hidden" name="reconciliationId" value={detail.id}/><input type="hidden" name="expectedVersion" value={detail.version}/><input type="hidden" name="selectedTransactionIds" value={JSON.stringify(selected)}/><div className="border-b border-border-subtle p-5"><h2 className="font-bold">Statement-cleared activity</h2><p className="mt-1 text-sm text-text-muted">Select only activity that appears on this statement. Server calculations use exact decimals.</p></div><div className="divide-y divide-border-subtle">{detail.candidates.map((item) => <label key={item.id} className="flex min-h-14 cursor-pointer items-center gap-3 p-4"><input className="h-5 w-5" type="checkbox" checked={selectedRows.has(item.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, item.id] : selected.filter((value) => value !== item.id))}/><span className="min-w-0 flex-1"><span className="block font-bold">{item.description}</span><span className="text-xs text-text-muted">{new Date(item.postedAt).toLocaleDateString()} · {item.direction.toLowerCase()}</span></span><span className="money-value font-bold">{item.direction === "OUTFLOW" ? "−" : "+"}${item.amount}</span></label>)}</div><div className="flex flex-wrap gap-3 p-5"><button className="min-h-11 rounded-[var(--radius-sm)] bg-brand-navy px-4 text-sm font-bold text-white">Save selection ({selected.length})</button>{saveState.message && <p role="status" className="self-center text-sm text-text-muted">{saveState.message}</p>}</div></form>}
  {editable && <form action={finalize} className="mt-5"><input type="hidden" name="reconciliationId" value={detail.id}/><input type="hidden" name="expectedVersion" value={detail.version}/><button className="min-h-11 rounded-[var(--radius-sm)] bg-brand-teal px-4 text-sm font-bold text-white">Finalize only at exact $0.00 difference</button>{finalizeState.message && <p role="status" className="mt-2 text-sm text-text-muted">{finalizeState.message}</p>}</form>}
 </>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-bold uppercase tracking-wide text-text-muted">{label}</p><p className="money-value mt-1 text-lg font-bold text-brand-navy">{value}</p></div>; }
