"use client";

import { useActionState } from "react";

import { Card, InlineAlert, PageHeader, StatusBadge } from "./ui";
import type { getSCorpCenter } from "@/lib/data/s-corp-center";

export type SCorpActionState = { status: "idle" | "success" | "error"; message: string | null };
const initial: SCorpActionState = { status: "idle", message: null };
type Data = Awaited<ReturnType<typeof getSCorpCenter>>;
type Action = (state: SCorpActionState, formData: FormData) => Promise<SCorpActionState>;
const statusCopy = (status: string) => status.replaceAll("_", " ");

export function SCorpCenter({ data, openingAction, adjustmentAction, debtAction, policyAction, healthAction }: { data: Data; openingAction: Action; adjustmentAction: Action; debtAction: Action; policyAction: Action; healthAction: Action }) {
  const [opening, submitOpening, openingPending] = useActionState(openingAction, initial);
  const [adjustment, submitAdjustment, adjustmentPending] = useActionState(adjustmentAction, initial);
  const [debt, submitDebt, debtPending] = useActionState(debtAction, initial);
  const [policy, submitPolicy, policyPending] = useActionState(policyAction, initial);
  const [health, submitHealth, healthPending] = useActionState(healthAction, initial);
  const basisStatus = data.readiness.basis.stock === "INCOMPLETE" || data.readiness.basis.debt === "INCOMPLETE" ? "BASIS WORKPAPER INCOMPLETE" : statusCopy(data.readiness.basis.stock);
  return <>
    <PageHeader eyebrow="Owner money" title="S-Corp workpaper center" description="Organize factual bookkeeping evidence and CPA-review items. This does not calculate a tax-free distribution or prepare a tax return." />
    <InlineAlert title="Professional review boundary" tone="info">Known amounts remain distinct from unknown workpaper facts. Book equity and shareholder-loan balances are not treated as tax basis.</InlineAlert>
    <section className="mt-6 grid gap-4 lg:grid-cols-2"><Card className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">Basis workpaper</h2><StatusBadge tone={basisStatus.includes("INCOMPLETE") ? "warning" : "info"}>{basisStatus}</StatusBadge></div><p className="mt-2 text-sm text-text-muted">Stock and debt basis are separate workpapers. Unknown amounts are intentionally not shown as $0.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Fact label="Stock opening" value={data.basis?.openingStockBasis ? `$${data.basis.openingStockBasis}` : "Unknown / incomplete"} /><Fact label="Debt opening" value={data.basis?.openingDebtBasis ? `$${data.basis.openingDebtBasis}` : "Unknown / incomplete"} /><Fact label="Current-through year" value={String(data.year)} /><Fact label="CPA review" value={data.basis?.reviewedAt ? "Recorded" : "Not recorded"} /></dl></Card><Card className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">Distribution readiness</h2><StatusBadge tone={data.readiness.status === "BLOCKED_BY_BOOKKEEPING" ? "warning" : "info"}>{statusCopy(data.readiness.status)}</StatusBadge></div><p className="mt-2 text-sm text-text-muted">A factual readiness check, not a tax conclusion or safe distribution amount.</p><ul className="mt-3 space-y-2 text-sm text-text-muted">{data.readiness.warnings.length ? data.readiness.warnings.map((warning) => <li key={warning}>• {warning}</li>) : <li>• No deterministic bookkeeping blockers are currently recorded.</li>}</ul></Card></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="p-5"><h2 className="font-bold">Opening basis workpaper</h2><form action={submitOpening} className="mt-3 grid gap-3 sm:grid-cols-2"><Input label="Tax year" name="taxYear" defaultValue={String(data.year)} required /><Input label="Effective date" name="effectiveDate" type="date" defaultValue={data.basis?.effectiveDate} /><Input label="Stock basis, if known" name="openingStockBasis" defaultValue={data.basis?.openingStockBasis ?? ""} /><Input label="Debt basis, if known" name="openingDebtBasis" defaultValue={data.basis?.openingDebtBasis ?? ""} /><Input label="Source / reference" name="sourceReference" defaultValue={data.basis?.sourceReference ?? ""} /><input type="hidden" name="version" value={data.basis?.version ?? ""} /><label className="text-sm font-bold text-text-muted sm:col-span-2"><input required className="mr-2" type="checkbox" name="ownerConfirmation" />I confirm these are approved workpaper facts or intentionally unknown.</label><ActionMessage state={opening} /><button disabled={openingPending} className="ui-button ui-button-primary min-h-11 px-4 sm:col-span-2">Save opening workpaper</button></form></Card>
      <Card className="p-5"><h2 className="font-bold">Basis workpaper adjustment</h2><p className="mt-1 text-sm text-text-muted">Use a specific documented workpaper category. This is not a generic ledger adjustment.</p>{data.basis ? <form action={submitAdjustment} className="mt-3 grid gap-3 sm:grid-cols-2"><input type="hidden" name="workpaperId" value={data.basis.id} /><Input label="Tax year" name="taxYear" defaultValue={String(data.year)} required /><Field label="Category"><select className="ui-input mt-1" name="category"><option value="CONTRIBUTION">Contribution</option><option value="DISTRIBUTION">Distribution</option><option value="SEPARATELY_STATED_INCOME">Separately stated income</option><option value="SEPARATELY_STATED_DEDUCTION">Separately stated deduction</option><option value="LOSS_LIMITATION">Loss limitation</option><option value="CPA_WORKPAPER_CORRECTION">CPA workpaper correction</option></select></Field><Input label="Amount" name="amount" required /><Input label="Source" name="source" required /><Input label="Reference" name="documentReference" /><label className="text-sm font-bold text-text-muted sm:col-span-2"><input required className="mr-2" type="checkbox" name="confirmation" />I confirm this classified adjustment and its source.</label><ActionMessage state={adjustment} /><button disabled={adjustmentPending} className="ui-button ui-button-secondary min-h-11 px-4 sm:col-span-2">Add adjustment</button></form> : <p className="mt-3 text-sm text-text-muted">Save an opening workpaper before adding an adjustment.</p>}</Card>
      <Card className="p-5"><h2 className="font-bold">Shareholder debt instruments</h2><p className="mt-1 text-sm text-text-muted">Book loan balance and tax debt-basis workpaper remain separate. Add an accounting reference only when you have one.</p><form action={submitDebt} className="mt-3 grid gap-3 sm:grid-cols-2"><Input label="Loan date" name="loanDate" type="date" required /><Input label="Instrument label" name="label" required /><Input label="Original principal" name="originalPrincipal" required /><Input label="Outstanding principal" name="outstandingPrincipal" required /><Input label="Tax debt basis, if known" name="taxBasisAmount" /><Input label="Book-loan reference" name="accountingReference" /><Input label="Written note reference" name="writtenNoteReference" /><Input label="CPA notes" name="cpaNotes" /><ActionMessage state={debt} /><button disabled={debtPending} className="ui-button ui-button-secondary min-h-11 px-4 sm:col-span-2">Add debt instrument</button></form><div className="mt-4 space-y-2">{data.debtInstruments.map((item) => <p key={item.id} className="border-t border-border-subtle pt-2 text-sm"><strong>{item.label}</strong> · outstanding ${item.outstandingPrincipal} · tax basis {item.taxBasisAmount ? `$${item.taxBasisAmount}` : "unknown / incomplete"}</p>)}</div></Card>
      <Card className="p-5"><h2 className="font-bold">Accounting policies</h2><p className="mt-1 text-sm text-text-muted">Consequential changes create a dated version; existing accounting remains tied to its historic evidence.</p><form action={submitPolicy} className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Policy"><select className="ui-input mt-1" name="policyType"><option value="ACCOUNTABLE_PLAN">Reimbursement / accountable plan</option><option value="RECEIPT_DOCUMENT">Receipt and document</option><option value="MERCHANT_CATEGORY">Merchant/category</option><option value="CAPITALIZATION">Capitalization</option><option value="PAYROLL_CLEARING">Payroll clearing</option><option value="COMPENSATION_WORKPAPER">Compensation workpaper</option><option value="CASH_TAX_RESERVE">Cash/tax reserve</option><option value="BOOKKEEPING_CUTOVER">Bookkeeping/cutover</option></select></Field><Input label="Policy title" name="title" required /><Input label="Effective date" name="effectiveDate" type="date" required /><Field label="Policy details"><textarea required className="ui-input mt-1 min-h-20" name="content" /></Field><Input label="Reason for version" name="reason" /><ActionMessage state={policy} /><button disabled={policyPending} className="ui-button ui-button-secondary min-h-11 px-4 sm:col-span-2">Save policy version</button></form><p className="mt-4 text-sm text-text-muted">{data.policies.some((item) => item.policyType === "ACCOUNTABLE_PLAN") ? "Accountable-plan policy configured." : "REIMBURSEMENT POLICY NEEDS REVIEW"}</p></Card>
      <Card className="p-5"><h2 className="font-bold">Shareholder benefits</h2><p className="mt-1 text-sm text-text-muted">Greater-than-2% shareholder health-insurance factual workpaper. No personal deduction eligibility or filing conclusion is made.</p><form action={submitHealth} className="mt-3 grid gap-3 sm:grid-cols-2"><Input label="Tax year" name="taxYear" defaultValue={String(data.year)} required /><Input label="Provider / policy" name="provider" defaultValue={data.benefit?.provider ?? ""} /><Input label="Coverage start" name="coverageStart" type="date" /><Input label="Coverage end" name="coverageEnd" type="date" /><Input label="Premium amount" name="premiumAmount" defaultValue={data.benefit?.premiumAmount ?? ""} /><Input label="Accounting source" name="paymentMethod" /><Field label="Payroll inclusion"><select className="ui-input mt-1" name="payrollInclusionStatus" defaultValue={data.benefit?.payrollInclusionStatus ?? "INCOMPLETE"}><option value="INCOMPLETE">Incomplete</option><option value="COMPLETE">Complete</option><option value="REVIEW_NEEDED">Review needed</option></select></Field><Field label="W-2 workpaper"><select className="ui-input mt-1" name="w2WorkpaperStatus" defaultValue={data.benefit?.w2WorkpaperStatus ?? "INCOMPLETE"}><option value="INCOMPLETE">Incomplete</option><option value="READY">Ready</option><option value="REVIEW_NEEDED">Review needed</option></select></Field><Field label="CPA review"><select className="ui-input mt-1" name="cpaReviewStatus" defaultValue={data.benefit?.cpaReviewStatus ?? "CPA_REVIEW"}><option value="CPA_REVIEW">CPA review</option><option value="COMPLETE">Complete</option></select></Field><Input label="Document reference" name="documentReference" /><ActionMessage state={health} /><button disabled={healthPending} className="ui-button ui-button-secondary min-h-11 px-4 sm:col-span-2">Save health-insurance workpaper</button></form></Card>
      <Card className="p-5"><h2 className="font-bold">Reimbursements and recorded distributions</h2><p className="mt-1 text-sm text-text-muted">Operational reimbursement states: needs documentation, ready for review, reimbursement due, payment detected, completed, or exception.</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(data.reimbursementStates).map(([state, count]) => <StatusBadge key={state} tone={state === "aging" && count ? "warning" : "neutral"}>{state === "aging" ? `${count} aging` : `${statusCopy(state)}: ${count}`}</StatusBadge>)}</div><h3 className="mt-5 text-sm font-bold">Historical distribution snapshots</h3>{data.snapshots.length ? <div className="mt-2 space-y-2">{data.snapshots.map((item) => <p key={item.id} className="border-t border-border-subtle pt-2 text-sm">{item.distributionDate ?? "Recorded distribution"} {item.amount ? `· $${item.amount}` : ""} · {statusCopy(item.status)} · {item.acknowledgedAt ? "acknowledged" : "acknowledgement not recorded"}</p>)}</div> : <p className="mt-2 text-sm text-text-muted">No recorded distribution snapshot yet.</p>}</Card>
    </section>
  </>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-text-muted">{label}{children}</label>; }
function Input({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <Field label={label}><input className="ui-input mt-1" {...props} /></Field>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold text-text-muted">{label}</dt><dd className="mt-1 font-bold">{value}</dd></div>; }
function ActionMessage({ state }: { state: SCorpActionState }) { return state.message ? <p role={state.status === "error" ? "alert" : "status"} className="text-sm font-bold sm:col-span-2">{state.message}</p> : null; }
