"use client";

import { useActionState, useMemo, useState } from "react";
import Link from "next/link";
import { InlineAlert, PageHeader, StatusBadge } from "./ui";
import { confirmImport, ignoreImportedTransaction, postImportedTransaction, previewImport } from "@/app/app/money/import/actions";

type Props = Awaited<ReturnType<typeof import("@/lib/services/financial-ingestion")["getImportWorkspace"]>>;
type ActionState = Awaited<ReturnType<typeof previewImport>>;
const initial: ActionState = { ok: false };
export function TransactionImportExperience({ accounts, categories, imports, items, profiles }: Props) {
  const [csvText, setCsvText] = useState(""); const [filename, setFilename] = useState(""); const [accountId, setAccountId] = useState(accounts[0]?.id ?? ""); const [selectedProfile, setSelectedProfile] = useState("");
  const [previewState, previewAction] = useActionState(previewImport, initial); const [confirmState, confirmAction] = useActionState(confirmImport, initial); const [postState, postAction] = useActionState(postImportedTransaction, initial); const [ignoreState, ignoreAction] = useActionState(ignoreImportedTransaction, initial);
  const profile = useMemo(() => profiles.find((item) => item.id === selectedProfile && item.financialAccountId === accountId), [profiles, selectedProfile, accountId]);
  async function chooseFile(file: File | undefined) { if (!file) return; setFilename(file.name); setCsvText(await file.text()); }
  const preview = previewState.preview;
  return <section className="space-y-7"><PageHeader eyebrow="Money / import" title="Import transactions" description="Upload your bank’s transaction CSV so Capture Tracker can prepare monthly activity for review. Bank categories are evidence, not accounting decisions." action={<Link className="ui-button ui-button-secondary min-h-11 rounded-[var(--radius-sm)] border border-border-subtle px-4 pt-3 text-sm font-bold" href="/app/money">Transaction review</Link>}/>
    <form action={previewAction} className="ui-card grid gap-4 p-5 sm:p-6"><input type="hidden" name="csvText" value={csvText}/><input type="hidden" name="sourceFilename" value={filename}/><input type="hidden" name="mapping" value={JSON.stringify(profile?.mappingJson ?? {})}/><label className="text-sm font-bold text-text-muted">Financial account<select required name="financialAccountId" value={accountId} onChange={(event) => { setAccountId(event.target.value); setSelectedProfile(""); }} className="ui-input mt-1">{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label className="text-sm font-bold text-text-muted">CSV file<input required type="file" accept=".csv,text/csv" onChange={(event) => void chooseFile(event.target.files?.[0])} className="ui-input mt-1"/></label><label className="text-sm font-bold text-text-muted">Saved mapping profile (optional)<select name="profileId" value={selectedProfile} onChange={(event) => setSelectedProfile(event.target.value)} className="ui-input mt-1"><option value="">Auto-detect from CSV headers</option>{profiles.filter((item) => item.financialAccountId === accountId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p className="text-xs leading-5 text-text-muted">Previewing stores mapping and outcome counts, never the uploaded CSV. File limit: 2 MB / 5,000 rows.</p><button disabled={!csvText || !accountId} className="ui-button ui-button-primary min-h-11 rounded-[var(--radius-sm)] bg-brand-navy px-4 text-sm font-bold text-white disabled:opacity-50">Preview normalized activity</button>{previewState.message && <InlineAlert title={previewState.ok ? "Preview ready" : "Preview unavailable"} tone={previewState.ok ? "success" : "warning"}>{previewState.message}</InlineAlert>}</form>
    {preview && <section className="ui-card p-5 sm:p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">Review import preview</h2><p className="mt-1 text-sm text-text-muted">Confirming adds activity to the review queue. It does not post journal entries.</p></div><div className="flex gap-2"><StatusBadge tone="success">{preview.summary.new} new</StatusBadge><StatusBadge tone="warning">{preview.summary.duplicate + preview.summary.possibleDuplicate} duplicates</StatusBadge><StatusBadge tone="warning">{preview.summary.invalid} invalid</StatusBadge></div></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-secondary text-text-muted"><tr><th className="p-3">Date</th><th className="p-3">Description</th><th className="p-3">State</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{preview.rows.slice(0, 100).map((row) => <tr key={row.rowNumber} className="border-t border-border-subtle"><td className="p-3">{row.date || "—"}</td><td className="p-3">{row.description}{row.reason && <p className="mt-1 text-xs text-text-muted">{row.reason}</p>}</td><td className="p-3"><StatusBadge tone={row.status === "NEW" ? "success" : "warning"}>{row.status.replaceAll("_", " ")}</StatusBadge></td><td className="money-value p-3 text-right">{row.amount && `${row.direction === "OUTFLOW" ? "-" : "+"}$${row.amount}`}</td></tr>)}</tbody></table></div><form action={confirmAction} className="mt-5 grid gap-3"><input type="hidden" name="importId" value={preview.importId}/><input type="hidden" name="csvText" value={csvText}/><input type="hidden" name="mapping" value={JSON.stringify(preview.mapping)}/><label className="text-sm font-bold text-text-muted">Save this mapping as (optional)<input name="saveProfileName" maxLength={100} className="ui-input mt-1" placeholder="e.g. Chase Business Checking"/></label><button className="ui-button ui-button-primary min-h-11 rounded-[var(--radius-sm)] bg-brand-navy px-4 text-sm font-bold text-white">Confirm import and open review queue</button>{confirmState.message && <InlineAlert title={confirmState.ok ? "Import complete" : "Import unavailable"} tone={confirmState.ok ? "success" : "warning"}>{confirmState.message}</InlineAlert>}</form></section>}
    <section className="ui-card overflow-hidden"><div className="border-b border-border-subtle p-5"><h2 className="font-bold">Imported activity needing attention</h2><p className="mt-1 text-sm text-text-muted">Only approved categories can create a balanced journal entry. Possible duplicates need a separate decision.</p></div>{items.length ? <div className="divide-y divide-border-subtle">{items.map((item) => <article key={item.id} className="grid gap-3 p-5 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap gap-2"><p className="font-bold">{item.description}</p><StatusBadge tone={item.status === "SUGGESTED" ? "info" : "warning"}>{item.status.replaceAll("_", " ")}</StatusBadge></div><p className="mt-1 text-sm text-text-muted">{item.date} · {item.financialAccount.name} · {item.direction === "OUTFLOW" ? "-" : "+"}${item.amount}</p>{item.suggestionReason && <p className="mt-2 text-xs text-text-muted">{item.suggestionReason}</p>}</div>{item.status === "POSSIBLE_DUPLICATE" ? <form action={ignoreAction}><input type="hidden" name="externalTransactionId" value={item.id}/><button className="ui-button ui-button-secondary min-h-11 rounded-[var(--radius-sm)] border border-border-subtle px-3 text-sm font-bold">Exclude from books</button></form> : <form action={postAction} className="flex flex-wrap gap-2"><input type="hidden" name="externalTransactionId" value={item.id}/><select required name="ledgerAccountId" defaultValue={item.suggestedLedgerAccountId ?? ""} className="ui-input min-h-11"><option value="">Choose {item.direction === "INFLOW" ? "income" : "expense"} category</option>{categories.filter((category) => category.type === (item.direction === "INFLOW" ? "INCOME" : "EXPENSE")).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><button className="ui-button ui-button-primary min-h-11 rounded-[var(--radius-sm)] bg-brand-navy px-3 text-sm font-bold text-white">Post</button></form>}</article>)}</div> : <p className="p-5 text-sm text-text-muted">No imported activity currently needs attention.</p>}{postState.message && <div className="p-5"><InlineAlert title={postState.ok ? "Posted" : "Posting unavailable"} tone={postState.ok ? "success" : "warning"}>{postState.message}</InlineAlert></div>}{ignoreState.message && <div className="p-5"><InlineAlert title={ignoreState.ok ? "Excluded" : "Request unavailable"} tone={ignoreState.ok ? "success" : "warning"}>{ignoreState.message}</InlineAlert></div>}</section>
    <section className="ui-card overflow-hidden"><div className="border-b border-border-subtle p-5"><h2 className="font-bold">Recent imports</h2></div><ul className="divide-y divide-border-subtle">{imports.map((item) => <li key={item.id} className="flex flex-wrap justify-between gap-3 p-4 text-sm"><div><p className="font-bold">{item.sourceFilename}</p><p className="text-text-muted">{item.financialAccount.name} · {item.createdAt.slice(0, 10)}</p></div><p className="text-text-muted">{item.newCount} new · {item.duplicateCount} duplicate · {item.possibleDuplicateCount} possible · {item.invalidCount} invalid</p></li>)}</ul></section>
  </section>;
}
