"use server";
import { revalidatePath } from "next/cache";
import { requireBusinessContext } from "@/lib/security/business-context";
import { completeWeeklyReview, reopenWeeklyReview, startWeeklyReview } from "@/lib/services/weekly-review";
export type WeeklyReviewActionState = { ok: boolean; message?: string };
const valid = (value: string) => /^[A-Za-z0-9_-]{1,191}$/.test(value);
export async function startAuthenticatedWeeklyReview(state: WeeklyReviewActionState): Promise<WeeklyReviewActionState> { void state; try { const context = await requireBusinessContext(); const result = await startWeeklyReview({ businessId: context.business.id, actorUserId: context.user.id }); if (!result.ok) return { ok: false, message: "The weekly review could not start safely." }; revalidatePath("/app/review"); return { ok: true, message: result.state === "EXISTING" ? "This week’s review is already available." : "Weekly review started." }; } catch { return { ok: false, message: "The weekly review could not be authorized." }; } }
export async function completeAuthenticatedWeeklyReview(_: WeeklyReviewActionState, form: FormData): Promise<WeeklyReviewActionState> { const reviewId = String(form.get("reviewId") ?? ""); if (!valid(reviewId)) return { ok: false, message: "The review is invalid." }; try { const context = await requireBusinessContext(); const result = await completeWeeklyReview({ businessId: context.business.id, actorUserId: context.user.id }, reviewId, String(form.get("note") ?? "")); if (!result.ok) return { ok: false, message: "The review could not be completed safely." }; revalidatePath("/app/review"); return { ok: true, message: result.state === "COMPLETED" ? `Review completed with ${result.unresolvedItemCount} items still needing attention.` : "This review was already completed." }; } catch { return { ok: false, message: "The review could not be authorized." }; } }
export async function reopenAuthenticatedWeeklyReview(_: WeeklyReviewActionState, form: FormData): Promise<WeeklyReviewActionState> { const reviewId = String(form.get("reviewId") ?? ""); if (!valid(reviewId)) return { ok: false, message: "The review is invalid." }; try { const context = await requireBusinessContext(); const result = await reopenWeeklyReview({ businessId: context.business.id, actorUserId: context.user.id }, reviewId); if (!result.ok) return { ok: false, message: "The review could not be reopened safely." }; revalidatePath("/app/review"); return { ok: true, message: result.state === "REOPENED" ? "Review reopened; prior completion evidence is retained." : "This review is already open." }; } catch { return { ok: false, message: "The review could not be authorized." }; } }
