"use server";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { requireBusinessContext } from "@/lib/security/business-context";
import { createCustomer, createInvoice, issueInvoice, recordInvoicePayment } from "@/lib/services/invoicing";
export type InvoiceActionState = { status: "idle" | "success" | "error"; message: string | null };
const actor = (context: Awaited<ReturnType<typeof requireBusinessContext>>) => ({ businessId: context.business.id, actorUserId: context.user.id, actorMembershipId: context.membership.id, role: context.membership.role, executionMode: "authenticated" as const });
export async function createCustomerAction(_: InvoiceActionState, formData: FormData): Promise<InvoiceActionState> { try { const context = await requireBusinessContext(); const result = await createCustomer(prisma, actor(context), Object.fromEntries(formData)); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/app/money/invoices"); return { status: "success", message: "Customer saved." }; } catch { return { status: "error", message: "Customer could not be saved safely." }; } }
export async function createInvoiceAction(_: InvoiceActionState, formData: FormData): Promise<InvoiceActionState> { try { const context = await requireBusinessContext(); const result = await createInvoice(prisma, actor(context), Object.fromEntries(formData)); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/app/money/invoices"); return { status: "success", message: `Draft ${result.invoiceNumber} created. Share link: /invoice/${result.publicToken}` }; } catch { return { status: "error", message: "Invoice could not be saved safely." }; } }
export async function issueInvoiceAction(_: InvoiceActionState, formData: FormData): Promise<InvoiceActionState> { try { const context = await requireBusinessContext(); const id = formData.get("invoiceId"); const result = await issueInvoice(prisma, actor(context), typeof id === "string" ? id : ""); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/app/money/invoices"); return { status: "success", message: result.accountingBasis === "NEEDS_REVIEW" ? "Invoice issued. ACCOUNTING POLICY NEEDS REVIEW before ledger treatment." : "Invoice issued." }; } catch { return { status: "error", message: "Invoice could not be issued safely." }; } }
export async function recordInvoicePaymentAction(_: InvoiceActionState, formData: FormData): Promise<InvoiceActionState> { try { const context = await requireBusinessContext(); const result = await recordInvoicePayment(prisma, actor(context), Object.fromEntries(formData)); if (!result.ok) return { status: "error", message: result.message }; revalidatePath("/app/money/invoices"); revalidatePath("/app/money"); revalidatePath("/app/today"); revalidatePath("/app/review"); return { status: "success", message: "Payment recorded and invoice status updated." }; } catch { return { status: "error", message: "Invoice payment could not be recorded safely." }; } }
