"use server";
import { revalidatePath } from "next/cache";
import { requireBusinessContext } from "@/lib/security/business-context";
import { prisma } from "@/lib/prisma";
import { createMileagePolicy, createMileageReimbursement, recordMileageTrip } from "@/lib/services/mileage";
export type MileageActionState = { status: "idle" | "success" | "error"; message: string | null };
const actor = (c: Awaited<ReturnType<typeof requireBusinessContext>>) => ({ businessId: c.business.id, actorUserId: c.user.id, actorMembershipId: c.membership.id, role: c.membership.role, executionMode: "authenticated" as const });
const refresh = () => { revalidatePath("/app/taxes/mileage"); revalidatePath("/app/taxes/owner-money"); revalidatePath("/app/today"); revalidatePath("/app/review"); };
export async function createMileagePolicyAction(_: MileageActionState, form: FormData): Promise<MileageActionState> { try { const c = await requireBusinessContext(); const r = await createMileagePolicy(prisma, actor(c), Object.fromEntries(form)); refresh(); return r.ok ? { status: "success", message: "Mileage policy saved." } : { status: "error", message: r.message }; } catch { return { status: "error", message: "Mileage policy could not be saved safely." }; } }
export async function recordMileageTripAction(_: MileageActionState, form: FormData): Promise<MileageActionState> { try { const c = await requireBusinessContext(); const r = await recordMileageTrip(prisma, actor(c), Object.fromEntries(form)); refresh(); return r.ok ? { status: "success", message: r.policyNeeded ? "Trip saved. MILEAGE POLICY NEEDS REVIEW before reimbursement." : `Trip saved. Reimbursement workpaper amount: $${r.reimbursementAmount}.` } : { status: "error", message: r.message }; } catch { return { status: "error", message: "Mileage trip could not be saved safely." }; } }
export async function createMileageReimbursementAction(_: MileageActionState, form: FormData): Promise<MileageActionState> { try { const c = await requireBusinessContext(); const r = await createMileageReimbursement(prisma, actor(c), String(form.get("tripId") ?? "")); refresh(); return r.ok ? { status: "success", message: "Mileage reimbursement claim created for controlled Owner Money approval." } : { status: "error", message: r.message }; } catch { return { status: "error", message: "Mileage reimbursement could not be created safely." }; } }
