import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { MileageCenter } from "@/components/mileage-center";
import { TaxesNav } from "@/components/taxes-nav";
import { prisma } from "@/lib/prisma";
import { isAccessControlError, requireBusinessContext } from "@/lib/security/business-context";
import { createMileagePolicyAction, createMileageReimbursementAction, recordMileageTripAction } from "./actions";
export const dynamic = "force-dynamic"; export const revalidate = 0;
export default async function MileagePage() { let c; try { c = await requireBusinessContext(); } catch (e) { if (isAccessControlError(e)) notFound(); throw e; } const [policies, trips] = await Promise.all([prisma.mileagePolicy.findMany({ where: { businessId: c.business.id }, orderBy: { effectiveDate: "desc" }, select: { id: true, effectiveDate: true, effectiveEndDate: true, ratePerMile: true, sourceReference: true } }), prisma.mileageTrip.findMany({ where: { businessId: c.business.id }, orderBy: { tripDate: "desc" }, select: { id: true, tripDate: true, originDescription: true, destinationDescription: true, businessPurpose: true, miles: true, reimbursementAmount: true, reimbursementClaimId: true }, take: 100 })]); return <AppShell mode="app" destination="taxes" businessName={c.business.displayName}><TaxesNav basePath="/app"/><MileageCenter policies={policies.map((p) => ({ id: p.id, effectiveDate: p.effectiveDate.toISOString().slice(0, 10), endDate: p.effectiveEndDate?.toISOString().slice(0, 10) ?? null, rate: p.ratePerMile.toFixed(4), source: p.sourceReference }))} trips={trips.map((t) => ({ id: t.id, date: t.tripDate.toISOString().slice(0, 10), origin: t.originDescription, destination: t.destinationDescription, purpose: t.businessPurpose, miles: t.miles.toFixed(2), amount: t.reimbursementAmount?.toFixed(2) ?? null, claimed: Boolean(t.reimbursementClaimId) }))} policyAction={createMileagePolicyAction} tripAction={recordMileageTripAction} reimbursementAction={createMileageReimbursementAction} canMutate={c.membership.role === "OWNER"}/></AppShell>; }
