import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { DocumentDetail } from "@/components/document-detail";
import { DocumentTransactionsPanel } from "@/components/transaction-document-links";
import { getDocument } from "@/lib/documents/service";
import { listEligibleTransactions, listLinkedTransactions } from "@/lib/documents/transaction-links";
import { resolveLocalDemoContext } from "@/lib/security/local-demo-context";
import { linkDemoDocument, unlinkDemoDocument } from "../../money/[transactionId]/actions";
import { transitionDemoDocument } from "../actions";
export const dynamic = "force-dynamic";
export default async function DemoDocumentPage({ params }: { params: Promise<{ documentId: string }> }) { const context = await resolveLocalDemoContext(); if (!context) notFound(); const document = await getDocument(context.businessId, (await params).documentId); if (!document) notFound(); const [linkedTransactions, eligibleTransactions] = await Promise.all([listLinkedTransactions(context.businessId, document.id), listEligibleTransactions(context.businessId, document.id)]); const actions = document.status === "PENDING_VALIDATION" ? <div className="mt-5 flex gap-3"><form action={transitionDemoDocument.bind(null, document.id, "ACTIVE")}><button className="min-h-11 rounded bg-brand-teal px-3 text-sm font-bold text-white">Mark active</button></form><form action={transitionDemoDocument.bind(null, document.id, "QUARANTINED")}><button className="min-h-11 rounded border border-border-subtle px-3 text-sm font-bold">Quarantine</button></form></div> : undefined; return <AppShell mode="demo" destination="documents" businessName={context.businessName}><DocumentDetail document={document} basePath="/demo" actions={actions} /><div className="mt-6"><DocumentTransactionsPanel documentId={document.id} basePath="/demo" linked={linkedTransactions.map((link) => ({ linkId: link.id, attachedAt: link.attachedAt.toISOString(), id: link.transaction.id, postedAt: link.transaction.postedAt.toISOString(), description: link.transaction.description, merchantName: link.transaction.merchantName, amount: link.transaction.amount.toFixed(2), direction: link.transaction.direction, accountName: link.transaction.account.name }))} eligible={eligibleTransactions.map((transaction) => ({ id: transaction.id, postedAt: transaction.postedAt.toISOString(), description: transaction.description, merchantName: transaction.merchantName, amount: transaction.amount.toFixed(2), direction: transaction.direction, accountName: transaction.account.name }))} linkAction={linkDemoDocument} unlinkAction={unlinkDemoDocument}/></div></AppShell>; }
