-- V2.2 operational-independence foundation. Additive only: all new workflows
-- begin empty and no historic accounting, customer, provider, or mileage data is inferred.
ALTER TYPE "BusinessRole" ADD VALUE IF NOT EXISTS 'CPA_READ_ONLY';
CREATE TYPE "BankConnectionState" AS ENUM ('CONNECTED','SYNCING','NEEDS_ATTENTION','RECONNECT_REQUIRED','DISCONNECTED');
CREATE TYPE "BankSyncStatus" AS ENUM ('STARTED','COMPLETED','FAILED');
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT','ISSUED','PARTIALLY_PAID','PAID','OVERDUE','VOID');
CREATE TYPE "BillStatus" AS ENUM ('DRAFT','REVIEW','APPROVED','DUE','PARTIALLY_PAID','PAID','VOID');

CREATE TABLE "BankConnection" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"providerId" VARCHAR(64) NOT NULL,"providerConnectionRef" VARCHAR(191) NOT NULL,"institutionName" VARCHAR(180),"state" "BankConnectionState" NOT NULL DEFAULT 'CONNECTED',"lastSuccessfulSyncAt" TIMESTAMP(3),"lastAttemptedSyncAt" TIMESTAMP(3),"syncCursor" VARCHAR(500),"errorCode" VARCHAR(100),"errorMessage" VARCHAR(500),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "BankConnection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ConnectedFinancialAccount" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"bankConnectionId" TEXT NOT NULL,"financialAccountId" TEXT,"externalAccountRef" VARCHAR(191) NOT NULL,"name" VARCHAR(180) NOT NULL,"accountType" VARCHAR(64) NOT NULL,"maskedLastFour" VARCHAR(4),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "ConnectedFinancialAccount_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BankSyncRun" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"bankConnectionId" TEXT NOT NULL,"status" "BankSyncStatus" NOT NULL DEFAULT 'STARTED',"cursorBefore" VARCHAR(500),"cursorAfter" VARCHAR(500),"importedCount" INTEGER NOT NULL DEFAULT 0,"duplicateCount" INTEGER NOT NULL DEFAULT 0,"updatedCount" INTEGER NOT NULL DEFAULT 0,"errorCode" VARCHAR(100),"errorMessage" VARCHAR(500),"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),CONSTRAINT "BankSyncRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BankProviderTransaction" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"bankConnectionId" TEXT NOT NULL,"connectedFinancialAccountId" TEXT NOT NULL,"bankSyncRunId" TEXT,"providerTransactionRef" VARCHAR(191) NOT NULL,"transactionDate" TIMESTAMP(3) NOT NULL,"postedDate" TIMESTAMP(3),"description" TEXT NOT NULL,"amount" DECIMAL(18,2) NOT NULL,"direction" "TransactionDirection" NOT NULL,"pending" BOOLEAN NOT NULL DEFAULT false,"providerUpdatedAt" TIMESTAMP(3),"normalizedExternalTransactionId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "BankProviderTransaction_pkey" PRIMARY KEY ("id"));

CREATE TABLE "Customer" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"businessName" VARCHAR(180) NOT NULL,"contactName" VARCHAR(180),"email" VARCHAR(320),"billingAddress" TEXT,"notes" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "Customer_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Invoice" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"customerId" TEXT NOT NULL,"invoiceNumber" VARCHAR(64) NOT NULL,"publicTokenHash" VARCHAR(64),"issueDate" TIMESTAMP(3),"dueDate" TIMESTAMP(3),"status" "InvoiceStatus" NOT NULL DEFAULT 'DRAFT',"subtotal" DECIMAL(18,2) NOT NULL DEFAULT 0,"discountAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,"taxAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,"total" DECIMAL(18,2) NOT NULL DEFAULT 0,"memo" TEXT,"paymentInstructions" TEXT,"terms" TEXT,"voidedAt" TIMESTAMP(3),"voidReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InvoiceLine" ("id" TEXT NOT NULL,"invoiceId" TEXT NOT NULL,"description" VARCHAR(500) NOT NULL,"quantity" DECIMAL(18,4) NOT NULL,"rate" DECIMAL(18,2) NOT NULL,"amount" DECIMAL(18,2) NOT NULL,"sortOrder" INTEGER NOT NULL,CONSTRAINT "InvoiceLine_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InvoicePayment" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"invoiceId" TEXT NOT NULL,"amount" DECIMAL(18,2) NOT NULL,"receivedAt" TIMESTAMP(3) NOT NULL,"externalTransactionId" TEXT,"reference" VARCHAR(500),"recordedByUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "InvoicePayment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CpaInvitation" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"invitedEmail" VARCHAR(320) NOT NULL,"tokenHash" VARCHAR(64) NOT NULL,"status" VARCHAR(32) NOT NULL DEFAULT 'PENDING',"expiresAt" TIMESTAMP(3) NOT NULL,"acceptedByUserId" TEXT,"acceptedAt" TIMESTAMP(3),"revokedAt" TIMESTAMP(3),"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CpaInvitation_pkey" PRIMARY KEY ("id"));

CREATE TABLE "Vendor" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"name" VARCHAR(180) NOT NULL,"contactName" VARCHAR(180),"email" VARCHAR(320),"defaultLedgerAccountId" TEXT,"paymentTerms" VARCHAR(180),"notes" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "Vendor_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Bill" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"vendorId" TEXT NOT NULL,"billNumber" VARCHAR(180),"billDate" TIMESTAMP(3),"dueDate" TIMESTAMP(3),"status" "BillStatus" NOT NULL DEFAULT 'DRAFT',"total" DECIMAL(18,2) NOT NULL DEFAULT 0,"memo" TEXT,"terms" TEXT,"supportingDocumentId" TEXT,"voidedAt" TIMESTAMP(3),"voidReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "Bill_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BillLine" ("id" TEXT NOT NULL,"billId" TEXT NOT NULL,"description" VARCHAR(500) NOT NULL,"ledgerAccountId" TEXT,"amount" DECIMAL(18,2) NOT NULL,"sortOrder" INTEGER NOT NULL,CONSTRAINT "BillLine_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BillPayment" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"billId" TEXT NOT NULL,"amount" DECIMAL(18,2) NOT NULL,"paidAt" TIMESTAMP(3) NOT NULL,"externalTransactionId" TEXT,"reference" VARCHAR(500),"recordedByUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "BillPayment_pkey" PRIMARY KEY ("id"));

CREATE TABLE "MileagePolicy" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"effectiveDate" TIMESTAMP(3) NOT NULL,"effectiveEndDate" TIMESTAMP(3),"ratePerMile" DECIMAL(8,4) NOT NULL,"sourceReference" VARCHAR(500) NOT NULL,"companyPolicy" TEXT,"version" INTEGER NOT NULL DEFAULT 1,"createdByUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "MileagePolicy_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MileageTrip" ("id" TEXT NOT NULL,"businessId" TEXT NOT NULL,"tripDate" TIMESTAMP(3) NOT NULL,"originDescription" VARCHAR(500) NOT NULL,"destinationDescription" VARCHAR(500) NOT NULL,"businessPurpose" VARCHAR(1000),"miles" DECIMAL(10,2) NOT NULL,"vehicleReference" VARCHAR(180),"notes" TEXT,"documentId" TEXT,"mileagePolicyId" TEXT,"reimbursementClaimId" TEXT,"reimbursementAmount" DECIMAL(18,2),"confirmedByUserId" TEXT,"confirmedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "MileageTrip_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "BankConnection_businessId_providerId_providerConnectionRef_key" ON "BankConnection"("businessId","providerId","providerConnectionRef"); CREATE INDEX "BankConnection_businessId_state_idx" ON "BankConnection"("businessId","state");
CREATE UNIQUE INDEX "ConnectedFinancialAccount_businessId_bankConnectionId_externalAccountRef_key" ON "ConnectedFinancialAccount"("businessId","bankConnectionId","externalAccountRef"); CREATE INDEX "ConnectedFinancialAccount_businessId_financialAccountId_idx" ON "ConnectedFinancialAccount"("businessId","financialAccountId");
CREATE UNIQUE INDEX "BankProviderTransaction_normalizedExternalTransactionId_key" ON "BankProviderTransaction"("normalizedExternalTransactionId"); CREATE UNIQUE INDEX "BankProviderTransaction_businessId_bankConnectionId_providerTransactionRef_key" ON "BankProviderTransaction"("businessId","bankConnectionId","providerTransactionRef");
CREATE UNIQUE INDEX "Customer_businessId_id_key" ON "Customer"("businessId","id"); CREATE INDEX "Customer_businessId_isActive_businessName_idx" ON "Customer"("businessId","isActive","businessName");
CREATE UNIQUE INDEX "Invoice_businessId_id_key" ON "Invoice"("businessId","id"); CREATE UNIQUE INDEX "Invoice_businessId_invoiceNumber_key" ON "Invoice"("businessId","invoiceNumber"); CREATE UNIQUE INDEX "Invoice_publicTokenHash_key" ON "Invoice"("publicTokenHash"); CREATE INDEX "Invoice_businessId_status_dueDate_idx" ON "Invoice"("businessId","status","dueDate");
CREATE UNIQUE INDEX "InvoiceLine_invoiceId_sortOrder_key" ON "InvoiceLine"("invoiceId","sortOrder"); CREATE UNIQUE INDEX "InvoicePayment_externalTransactionId_key" ON "InvoicePayment"("externalTransactionId"); CREATE INDEX "InvoicePayment_businessId_invoiceId_receivedAt_idx" ON "InvoicePayment"("businessId","invoiceId","receivedAt");
CREATE UNIQUE INDEX "CpaInvitation_tokenHash_key" ON "CpaInvitation"("tokenHash"); CREATE INDEX "CpaInvitation_businessId_status_expiresAt_idx" ON "CpaInvitation"("businessId","status","expiresAt");
CREATE UNIQUE INDEX "Vendor_businessId_id_key" ON "Vendor"("businessId","id"); CREATE INDEX "Vendor_businessId_isActive_name_idx" ON "Vendor"("businessId","isActive","name"); CREATE UNIQUE INDEX "Bill_businessId_id_key" ON "Bill"("businessId","id"); CREATE INDEX "Bill_businessId_status_dueDate_idx" ON "Bill"("businessId","status","dueDate"); CREATE UNIQUE INDEX "BillLine_billId_sortOrder_key" ON "BillLine"("billId","sortOrder"); CREATE UNIQUE INDEX "BillPayment_externalTransactionId_key" ON "BillPayment"("externalTransactionId"); CREATE INDEX "BillPayment_businessId_billId_paidAt_idx" ON "BillPayment"("businessId","billId","paidAt");
CREATE UNIQUE INDEX "MileagePolicy_businessId_id_key" ON "MileagePolicy"("businessId","id"); CREATE INDEX "MileagePolicy_businessId_effectiveDate_idx" ON "MileagePolicy"("businessId","effectiveDate"); CREATE UNIQUE INDEX "MileageTrip_businessId_id_key" ON "MileageTrip"("businessId","id"); CREATE INDEX "MileageTrip_businessId_tripDate_idx" ON "MileageTrip"("businessId","tripDate"); CREATE INDEX "MileageTrip_businessId_reimbursementClaimId_idx" ON "MileageTrip"("businessId","reimbursementClaimId");

ALTER TABLE "BankConnection" ADD CONSTRAINT "BankConnection_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT; ALTER TABLE "ConnectedFinancialAccount" ADD CONSTRAINT "ConnectedFinancialAccount_connection_fkey" FOREIGN KEY ("bankConnectionId") REFERENCES "BankConnection"("id") ON DELETE RESTRICT; ALTER TABLE "BankSyncRun" ADD CONSTRAINT "BankSyncRun_connection_fkey" FOREIGN KEY ("bankConnectionId") REFERENCES "BankConnection"("id") ON DELETE RESTRICT; ALTER TABLE "BankProviderTransaction" ADD CONSTRAINT "BankProviderTransaction_connection_fkey" FOREIGN KEY ("bankConnectionId") REFERENCES "BankConnection"("id") ON DELETE RESTRICT; ALTER TABLE "Customer" ADD CONSTRAINT "Customer_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT; ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_customer_fkey" FOREIGN KEY ("businessId","customerId") REFERENCES "Customer"("businessId","id") ON DELETE RESTRICT; ALTER TABLE "InvoiceLine" ADD CONSTRAINT "InvoiceLine_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT; ALTER TABLE "InvoicePayment" ADD CONSTRAINT "InvoicePayment_invoice_fkey" FOREIGN KEY ("businessId","invoiceId") REFERENCES "Invoice"("businessId","id") ON DELETE RESTRICT; ALTER TABLE "CpaInvitation" ADD CONSTRAINT "CpaInvitation_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT; ALTER TABLE "Vendor" ADD CONSTRAINT "Vendor_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT; ALTER TABLE "Bill" ADD CONSTRAINT "Bill_vendor_fkey" FOREIGN KEY ("businessId","vendorId") REFERENCES "Vendor"("businessId","id") ON DELETE RESTRICT; ALTER TABLE "BillLine" ADD CONSTRAINT "BillLine_billId_fkey" FOREIGN KEY ("billId") REFERENCES "Bill"("id") ON DELETE RESTRICT; ALTER TABLE "BillPayment" ADD CONSTRAINT "BillPayment_bill_fkey" FOREIGN KEY ("businessId","billId") REFERENCES "Bill"("businessId","id") ON DELETE RESTRICT; ALTER TABLE "MileagePolicy" ADD CONSTRAINT "MileagePolicy_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE RESTRICT; ALTER TABLE "MileageTrip" ADD CONSTRAINT "MileageTrip_policy_fkey" FOREIGN KEY ("businessId","mileagePolicyId") REFERENCES "MileagePolicy"("businessId","id") ON DELETE RESTRICT;
