import "server-only";
import { Prisma, type PrismaClient } from "@/generated/prisma/client";
import { mileageAmount } from "./operational-independence-core";
type Db = PrismaClient;
type Actor = { businessId: string; actorUserId: string; actorMembershipId: string; role: "OWNER" | "ADVISOR" | "CPA_READ_ONLY"; executionMode: "authenticated" | "demo" };
const text = (v: unknown, max = 500) => typeof v === "string" && v.trim() && v.trim().length <= max ? v.trim() : null;
const date = (v: unknown) => typeof v === "string" && /^\d{4}-\d{2}-\d{2}$/.test(v) ? new Date(`${v}T12:00:00.000Z`) : null;
const positive = (v: unknown, scale = 2) => typeof v === "string" && new RegExp(`^\\d{1,15}(?:\\.\\d{1,${scale}})?$`).test(v) && new Prisma.Decimal(v).greaterThan(0) ? new Prisma.Decimal(v) : null;
const audit = (actor: Actor, type: string, id: string, action: "CREATE" | "UPDATE", afterJson: Prisma.InputJsonValue) => ({ actorType: "USER" as const, businessId: actor.businessId, actorMembershipId: actor.actorMembershipId, action, entityType: type, entityId: id, afterJson, metadataJson: { v2_2: true, mileage: true, executionMode: actor.executionMode } });

export async function createMileagePolicy(client: Db, actor: Actor, raw: Record<string, unknown>) {
  if (actor.role !== "OWNER") return { ok: false as const, message: "Only the business owner can create a mileage policy." };
  const effectiveDate = date(raw.effectiveDate), effectiveEndDate = raw.effectiveEndDate ? date(raw.effectiveEndDate) : null, ratePerMile = positive(raw.ratePerMile, 4), sourceReference = text(raw.sourceReference, 500);
  if (!effectiveDate || !ratePerMile || !sourceReference || (effectiveEndDate && effectiveEndDate < effectiveDate)) return { ok: false as const, message: "Enter an effective date, positive rate, authoritative source, and valid date range." };
  const policy = await client.mileagePolicy.create({ data: { businessId: actor.businessId, effectiveDate, effectiveEndDate, ratePerMile, sourceReference, companyPolicy: text(raw.companyPolicy, 4000), createdByUserId: actor.actorUserId } }); await client.auditEvent.create({ data: audit(actor, "MileagePolicy", policy.id, "CREATE", { ratePerMile: ratePerMile.toFixed(4), sourceReference }) }); return { ok: true as const, id: policy.id };
}
export async function recordMileageTrip(client: Db, actor: Actor, raw: Record<string, unknown>) {
  if (actor.role !== "OWNER") return { ok: false as const, message: "Only the business owner can record mileage." };
  const tripDate = date(raw.tripDate), originDescription = text(raw.originDescription), destinationDescription = text(raw.destinationDescription), businessPurpose = text(raw.businessPurpose, 1000), miles = positive(raw.miles, 2), documentId = text(raw.documentId, 191);
  if (!tripDate || !originDescription || !destinationDescription || !businessPurpose || !miles) return { ok: false as const, message: "Trip date, origin, destination, business purpose, and positive miles are required." };
  return client.$transaction(async (tx) => { const [policy, document] = await Promise.all([tx.mileagePolicy.findFirst({ where: { businessId: actor.businessId, effectiveDate: { lte: tripDate }, OR: [{ effectiveEndDate: null }, { effectiveEndDate: { gte: tripDate } }] }, orderBy: { effectiveDate: "desc" } }), documentId ? tx.document.findFirst({ where: { id: documentId, businessId: actor.businessId, status: "ACTIVE", malwareScanStatus: "CLEAN" }, select: { id: true } }) : Promise.resolve(null)]); if (documentId && !document) return { ok: false as const, message: "The supporting document is unavailable." }; const amount = policy ? new Prisma.Decimal(mileageAmount(miles.toFixed(2), policy.ratePerMile.toFixed(4))) : null; const trip = await tx.mileageTrip.create({ data: { businessId: actor.businessId, tripDate, originDescription, destinationDescription, businessPurpose, miles, vehicleReference: text(raw.vehicleReference, 180), notes: text(raw.notes, 4000), documentId, mileagePolicyId: policy?.id, reimbursementAmount: amount, confirmedByUserId: actor.actorUserId, confirmedAt: new Date() } }); await tx.auditEvent.create({ data: audit(actor, "MileageTrip", trip.id, "CREATE", { miles: miles.toFixed(2), reimbursementAmount: amount?.toFixed(2) ?? null, policy: policy ? "APPLIED" : "MILEAGE_POLICY_NEEDS_REVIEW" }) }); return { ok: true as const, id: trip.id, reimbursementAmount: amount?.toFixed(2) ?? null, policyNeeded: !policy }; });
}
export async function createMileageReimbursement(client: Db, actor: Actor, tripId: string) {
  if (actor.role !== "OWNER") return { ok: false as const, message: "Only the business owner can create a mileage reimbursement." };
  return client.$transaction(async (tx) => { const trip = await tx.mileageTrip.findFirst({ where: { id: tripId, businessId: actor.businessId, reimbursementClaimId: null }, select: { id: true, tripDate: true, businessPurpose: true, reimbursementAmount: true, documentId: true } }); if (!trip || !trip.reimbursementAmount || !trip.businessPurpose) return { ok: false as const, message: "This trip needs a substantiated mileage policy and rate before reimbursement." }; const claim = await tx.reimbursementClaim.create({ data: { businessId: actor.businessId, claimantMembershipId: actor.actorUserId, totalAmount: trip.reimbursementAmount, notes: `Mileage trip ${trip.id}` } }); await tx.reimbursementExpense.create({ data: { businessId: actor.businessId, claimId: claim.id, expenseType: "MILEAGE", documentId: trip.documentId, incurredAt: trip.tripDate, amount: trip.reimbursementAmount, businessPurpose: trip.businessPurpose, merchantName: "Mileage reimbursement" } }); await tx.mileageTrip.update({ where: { id: trip.id }, data: { reimbursementClaimId: claim.id, version: { increment: 1 } } }); await tx.auditEvent.create({ data: audit(actor, "MileageTrip", trip.id, "UPDATE", { reimbursementClaimId: claim.id, amount: trip.reimbursementAmount.toFixed(2) }) }); return { ok: true as const, claimId: claim.id }; });
}
