import "server-only";
import { getFinancialReports } from "@/lib/data/reports";
import { prisma } from "@/lib/prisma";

export type PilotActor = { businessId: string; actorUserId: string };
const periods = new Set(["month", "last-month", "quarter", "ytd", "previous-year"]);
const safe = (value: string) => (/^[=+\-@]/.test(value) ? `'${value}` : value.replaceAll('"', '""'));
const text = (v: FormDataEntryValue | null, max: number) => typeof v === "string" ? v.replace(/[<>]/g, "").trim().slice(0, max) : "";

export async function getPilotState(businessId: string) { const [business, onboarding, settings, exports] = await Promise.all([prisma.business.findUnique({ where: { id: businessId }, select: { displayName: true, legalName: true, timezone: true, fiscalYearStartMonth: true, currency: true } }), prisma.businessOnboarding.findUnique({ where: { businessId } }), prisma.businessSettings.findUnique({ where: { businessId } }), prisma.exportAudit.findMany({ where: { businessId }, orderBy: { createdAt: "desc" }, take: 10 })]); return { business, onboarding, settings, exports }; }
export async function saveOnboarding(actor: PilotActor, form: FormData) { const ownerDisplayName = text(form.get("ownerDisplayName"), 120); const displayName = text(form.get("displayName"), 120); const description = text(form.get("description"), 500) || null; const timezone = text(form.get("timezone"), 64); const fiscal = Number(form.get("fiscalYearStartMonth")); if (!ownerDisplayName || !displayName || !/^America\/[A-Za-z_]+$/.test(timezone) || !Number.isInteger(fiscal) || fiscal < 1 || fiscal > 12) return false; const complete = form.get("fictionalAcknowledged") === "on" && form.get("chartConfirmed") === "on"; await prisma.$transaction(async (tx) => { await tx.business.update({ where: { id: actor.businessId }, data: { displayName, timezone, fiscalYearStartMonth: fiscal } }); await tx.businessOnboarding.upsert({ where: { businessId: actor.businessId }, create: { businessId: actor.businessId, actorUserId: actor.actorUserId, ownerDisplayName, description, fictionalAcknowledged: complete, chartConfirmed: complete, status: complete ? "COMPLETED" : "IN_PROGRESS", completedAt: complete ? new Date() : null }, update: { actorUserId: actor.actorUserId, ownerDisplayName, description, fictionalAcknowledged: complete, chartConfirmed: complete, status: complete ? "COMPLETED" : "IN_PROGRESS", completedAt: complete ? new Date() : null } }); }); return true; }
export async function saveSettings(actor: PilotActor, form: FormData) { const defaultReportPeriod = text(form.get("defaultReportPeriod"), 24); const weeklyReviewDay = Number(form.get("weeklyReviewDay")); const retentionMonths = Number(form.get("retentionMonths")); if (!periods.has(defaultReportPeriod) || !Number.isInteger(weeklyReviewDay) || weeklyReviewDay < 0 || weeklyReviewDay > 6 || !Number.isInteger(retentionMonths) || retentionMonths < 12 || retentionMonths > 120) return false; await prisma.$transaction(async (tx) => { await tx.businessSettings.upsert({ where: { businessId: actor.businessId }, create: { businessId: actor.businessId, defaultReportPeriod, weeklyReviewDay, retentionMonths }, update: { defaultReportPeriod, weeklyReviewDay, retentionMonths } }); await tx.businessSettingsHistory.create({ data: { businessId: actor.businessId, actorUserId: actor.actorUserId, changedJson: { defaultReportPeriod, weeklyReviewDay, retentionMonths } } }); }); return true; }
export type ActivityQuery = { module?: string; q?: string; from?: string; to?: string; order?: string; page?: string; size?: string };
const activityModules = new Set(["Accounting", "Documents", "Weekly Review", "Ask AI", "Settings", "Exports"]);
// The query parameter is named `module`; this local variable is not the Node module object.
// eslint-disable-next-line @next/next/no-assign-module-variable
export async function getActivity(businessId: string, raw: ActivityQuery = {}) { const module = activityModules.has(raw.module ?? "") ? raw.module! : undefined; const q = (raw.q ?? "").replace(/[<>]/g, "").trim().slice(0, 80).toLowerCase(); const from = /^\d{4}-\d\d-\d\d$/.test(raw.from ?? "") ? new Date(`${raw.from}T00:00:00.000Z`) : undefined; const to = /^\d{4}-\d\d-\d\d$/.test(raw.to ?? "") ? new Date(`${raw.to}T23:59:59.999Z`) : undefined; const descending = raw.order !== "oldest"; const page = Math.max(1, Math.min(500, Number(raw.page) || 1)); const size = Math.max(5, Math.min(50, Number(raw.size) || 20)); const [audits, docs, reviews, ai, settings, exports] = await Promise.all([prisma.auditEvent.findMany({ where: { businessId }, orderBy: { occurredAt: "desc" }, take: 100, select: { id:true,entityType: true, action: true, occurredAt: true, reason: true } }), prisma.documentStatusHistory.findMany({ where: { businessId }, orderBy: { createdAt: "desc" }, take: 100, select: { id:true,newStatus: true, createdAt: true, reasonCode: true } }), prisma.weeklyReviewHistory.findMany({ where: { businessId }, orderBy: { createdAt: "desc" }, take: 100, select: { id:true,action: true, createdAt: true } }), prisma.askAiEvent.findMany({ where: { businessId }, orderBy: { createdAt: "desc" }, take: 100, select: { id:true,action: true, createdAt: true } }), prisma.businessSettingsHistory.findMany({ where: { businessId }, orderBy: { createdAt: "desc" }, take: 100, select: { id:true,createdAt: true } }), prisma.exportAudit.findMany({ where: { businessId }, orderBy: { createdAt: "desc" }, take: 100, select: { id:true,kind: true, createdAt: true, rowCount: true } })]); const all=[...audits.map(x=>({key:`audit-${x.id}`,module:"Accounting",label:`${x.action.toLowerCase()} ${x.entityType}`,at:x.occurredAt,detail:x.reason})),...docs.map(x=>({key:`document-${x.id}`,module:"Documents",label:`document ${x.newStatus.toLowerCase()}`,at:x.createdAt,detail:x.reasonCode})),...reviews.map(x=>({key:`review-${x.id}`,module:"Weekly Review",label:x.action.toLowerCase().replaceAll("_"," "),at:x.createdAt,detail:null})),...ai.map(x=>({key:`ai-${x.id}`,module:"Ask AI",label:x.action.toLowerCase().replaceAll("_"," "),at:x.createdAt,detail:null})),...settings.map(x=>({key:`settings-${x.id}`,module:"Settings",label:"settings changed",at:x.createdAt,detail:null})),...exports.map(x=>({key:`export-${x.id}`,module:"Exports",label:`${x.kind.toLowerCase()} export created`,at:x.createdAt,detail:`${x.rowCount} rows`}))].filter(x=>(!module||x.module===module)&&(!from||x.at>=from)&&(!to||x.at<=to)&&(!q||`${x.label} ${x.detail??""} ${x.module}`.toLowerCase().includes(q))).sort((a,b)=>descending?(b.at.getTime()-a.at.getTime()||b.key.localeCompare(a.key)):(a.at.getTime()-b.at.getTime()||a.key.localeCompare(b.key))); return {events:all.slice((page-1)*size,page*size),total:all.length,page,size,filters:{module:module??"",q,from:raw.from??"",to:raw.to??"",order:descending?"newest":"oldest"}}; }
export async function buildExport(actor: PilotActor, kind: string) { const valid = ["TRANSACTIONS", "JOURNAL", "ACCOUNTS", "REPORTS", "DOCUMENTS", "DOCUMENT_LINKS", "WEEKLY_REVIEW", "ASK_AI"] as const; if (!valid.includes(kind as typeof valid[number])) return null; let headers: string[] = []; let rows: string[][] = []; if (kind === "TRANSACTIONS") { const records = await prisma.transaction.findMany({ where: { businessId: actor.businessId }, orderBy: { postedAt: "desc" }, take: 1000, select: { postedAt: true, description: true, merchantName: true, amount: true, status: true, intent: true } }); headers=["Posted date","Description","Merchant","Amount","Status","Intent"]; rows=records.map(x=>[x.postedAt.toISOString().slice(0,10),x.description,x.merchantName??"",x.amount.toFixed(2),x.status,x.intent]); } else if (kind === "ACCOUNTS") { const records=await prisma.ledgerAccount.findMany({where:{businessId:actor.businessId},orderBy:{code:"asc"},take:500,select:{code:true,name:true,type:true,normalBalance:true}}); headers=["Code","Name","Type","Normal balance"]; rows=records.map(x=>[x.code,x.name,x.type,x.normalBalance]); } else if (kind === "DOCUMENTS") { const records=await prisma.document.findMany({where:{businessId:actor.businessId},take:1000,select:{displayName:true,type:true,category:true,status:true,uploadedAt:true}}); headers=["Name","Type","Category","Status","Uploaded"]; rows=records.map(x=>[x.displayName,x.type,x.category,x.status,x.uploadedAt.toISOString()]); } else if (kind === "WEEKLY_REVIEW") { const records=await prisma.weeklyReviewHistory.findMany({where:{businessId:actor.businessId},take:1000,orderBy:{createdAt:"desc"},select:{action:true,section:true,unresolvedItemCount:true,createdAt:true}}); headers=["Action","Section","Unresolved items","Recorded"]; rows=records.map(x=>[x.action,x.section??"",String(x.unresolvedItemCount??""),x.createdAt.toISOString()]); } else { const report=await getFinancialReports(actor.businessId); headers=["Report","Period","Value"]; rows=[["Profit and Loss income",report.range.label,report.profitAndLoss.totalIncome],["Profit and Loss expenses",report.range.label,report.profitAndLoss.totalExpenses],["Profit and Loss net income",report.range.label,report.profitAndLoss.netIncome],["Cash ending",report.range.label,report.cashActivity.endingCash]]; }
  const csv = [headers, ...rows].map(row => row.map(value => `"${safe(value)}"`).join(",")).join("\n"); const manifest={ kind, rows: rows.length, excluded:["document bytes","storage keys","private grants","secrets","hidden reasoning"] }; await prisma.exportAudit.create({data:{businessId:actor.businessId,actorUserId:actor.actorUserId,kind:kind as typeof valid[number],rowCount:rows.length,manifest}}); return { csv, filename:`capture-tracker-${kind.toLowerCase()}.csv`, manifest };
}
