import "server-only";

import { prisma } from "@/lib/prisma";
import {
  loadWeeklyReviewTaskCount,
  loadWeeklyReviewTasks,
} from "@/lib/services/weekly-review-tasks";

export type WeeklyReviewActor = { businessId: string; actorUserId: string };
const week = (value = new Date()) => { const day = new Date(Date.UTC(value.getUTCFullYear(), value.getUTCMonth(), value.getUTCDate())); const offset = (day.getUTCDay() + 6) % 7; day.setUTCDate(day.getUTCDate() - offset); const end = new Date(day); end.setUTCDate(end.getUTCDate() + 6); end.setUTCHours(23, 59, 59, 999); return { start: day, end }; };
export async function getWeeklyReview(businessId: string) { const [review, tasks] = await Promise.all([prisma.weeklyReview.findFirst({ where: { businessId }, include: { history: { orderBy: [{ createdAt: "asc" }, { id: "asc" }], take: 100 } }, orderBy: [{ weekStart: "desc" }, { id: "desc" }] }), loadWeeklyReviewTasks(prisma, businessId)]); return { review: review ? { id: review.id, status: review.status, weekStart: review.weekStart.toISOString(), weekEnd: review.weekEnd.toISOString(), unresolvedItemCount: review.unresolvedItemCount, completedAt: review.completedAt?.toISOString() ?? null, history: review.history.map((event) => ({ id: event.id, action: event.action, section: event.section, unresolvedItemCount: event.unresolvedItemCount, createdAt: event.createdAt.toISOString() })) } : null, tasks }; }
export async function startWeeklyReview(actor: WeeklyReviewActor, now = new Date()) { const period = week(now); try { return await prisma.$transaction(async (tx) => { const existing = await tx.weeklyReview.findFirst({ where: { businessId: actor.businessId, weekStart: period.start }, select: { id: true } }); if (existing) return { ok: true as const, state: "EXISTING" as const, reviewId: existing.id }; const review = await tx.weeklyReview.create({ data: { businessId: actor.businessId, weekStart: period.start, weekEnd: period.end, startedByUserId: actor.actorUserId, startedAt: new Date(), history: { create: { action: "STARTED", actorUserId: actor.actorUserId } } } }); return { ok: true as const, state: "STARTED" as const, reviewId: review.id }; }); } catch { const existing = await prisma.weeklyReview.findFirst({ where: { businessId: actor.businessId, weekStart: period.start }, select: { id: true } }); return existing ? { ok: true as const, state: "EXISTING" as const, reviewId: existing.id } : { ok: false as const, code: "UNAVAILABLE" as const }; } }
export async function completeWeeklyReview(actor: WeeklyReviewActor, reviewId: string, note?: string) { try { return await prisma.$transaction(async (tx) => { const review = await tx.weeklyReview.findFirst({ where: { id: reviewId, businessId: actor.businessId }, select: { id: true, status: true } }); if (!review) return { ok: false as const, code: "NOT_FOUND" as const }; if (review.status === "COMPLETED") return { ok: true as const, state: "ALREADY_COMPLETED" as const }; if (review.status !== "OPEN") return { ok: false as const, code: "INVALID" as const }; const unresolvedItemCount = await loadWeeklyReviewTaskCount(tx, actor.businessId); const updated = await tx.weeklyReview.updateMany({ where: { id: reviewId, businessId: actor.businessId, status: "OPEN" }, data: { status: "COMPLETED", completedAt: new Date(), completedByUserId: actor.actorUserId, completionNote: note?.trim().slice(0, 500) || null, unresolvedItemCount } }); if (!updated.count) return { ok: true as const, state: "ALREADY_COMPLETED" as const }; await tx.weeklyReviewHistory.create({ data: { businessId: actor.businessId, weeklyReviewId: reviewId, action: "COMPLETED", actorUserId: actor.actorUserId, unresolvedItemCount, note: note?.trim().slice(0, 500) || null } }); return { ok: true as const, state: "COMPLETED" as const, unresolvedItemCount }; }); } catch { return { ok: false as const, code: "UNAVAILABLE" as const }; } }
export async function reopenWeeklyReview(actor: WeeklyReviewActor, reviewId: string) { try { return await prisma.$transaction(async (tx) => { const updated = await tx.weeklyReview.updateMany({ where: { id: reviewId, businessId: actor.businessId, status: "COMPLETED" }, data: { status: "OPEN", completedAt: null, completedByUserId: null, completionNote: null, unresolvedItemCount: null } }); if (!updated.count) { const exists = await tx.weeklyReview.findFirst({ where: { id: reviewId, businessId: actor.businessId }, select: { status: true } }); return exists?.status === "OPEN" ? { ok: true as const, state: "ALREADY_OPEN" as const } : { ok: false as const, code: "NOT_FOUND" as const }; } await tx.weeklyReviewHistory.create({ data: { businessId: actor.businessId, weeklyReviewId: reviewId, action: "REOPENED", actorUserId: actor.actorUserId } }); return { ok: true as const, state: "REOPENED" as const }; }); } catch { return { ok: false as const, code: "UNAVAILABLE" as const }; } }
